// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ArcheryRoundResultToC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ArcheryRoundResultToC.proto</summary>
public static partial class ArcheryRoundResultToCReflection {

  #region Descriptor
  /// <summary>File descriptor for ArcheryRoundResultToC.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ArcheryRoundResultToCReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtBcmNoZXJ5Um91bmRSZXN1bHRUb0MucHJvdG8iiwEKGEFyY2hlcnlSb3Vu",
          "ZFBsYWNlbWVudFRvQxISCgpzaG9vdGVyX2lkGAEgASgJEgsKA2hpdBgCIAEo",
          "CBIOCgZmYWNlX3gYAyABKAISDgoGZmFjZV95GAQgASgCEhAKCGRpc3RhbmNl",
          "GAUgASgCEgwKBHJhbmsYBiABKAUSDgoGcG9pbnRzGAcgASgFIm8KFUFyY2hl",
          "cnlSb3VuZFJlc3VsdFRvQxITCgtyb3VuZF9pbmRleBgBIAEoBRISCgptdWx0",
          "aXBsaWVyGAIgASgFEi0KCnBsYWNlbWVudHMYAyADKAsyGS5BcmNoZXJ5Um91",
          "bmRQbGFjZW1lbnRUb0NiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ArcheryRoundPlacementToC), global::ArcheryRoundPlacementToC.Parser, new[]{ "ShooterId", "Hit", "FaceX", "FaceY", "Distance", "Rank", "Points" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ArcheryRoundResultToC), global::ArcheryRoundResultToC.Parser, new[]{ "RoundIndex", "Multiplier", "Placements" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// WorldEventToC oneof 안에 담기는 payload. 따로 보내는 패킷이 아니다.
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ArcheryRoundPlacementToC : pb::IMessage<ArcheryRoundPlacementToC>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ArcheryRoundPlacementToC> _parser = new pb::MessageParser<ArcheryRoundPlacementToC>(() => new ArcheryRoundPlacementToC());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ArcheryRoundPlacementToC> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ArcheryRoundResultToCReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryRoundPlacementToC() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryRoundPlacementToC(ArcheryRoundPlacementToC other) : this() {
    shooterId_ = other.shooterId_;
    hit_ = other.hit_;
    faceX_ = other.faceX_;
    faceY_ = other.faceY_;
    distance_ = other.distance_;
    rank_ = other.rank_;
    points_ = other.points_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryRoundPlacementToC Clone() {
    return new ArcheryRoundPlacementToC(this);
  }

  /// <summary>Field number for the "shooter_id" field.</summary>
  public const int ShooterIdFieldNumber = 1;
  private string shooterId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ShooterId {
    get { return shooterId_; }
    set {
      shooterId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "hit" field.</summary>
  public const int HitFieldNumber = 2;
  private bool hit_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Hit {
    get { return hit_; }
    set {
      hit_ = value;
    }
  }

  /// <summary>Field number for the "face_x" field.</summary>
  public const int FaceXFieldNumber = 3;
  private float faceX_;
  /// <summary>
  /// 미터, 사수 기준 오른쪽
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float FaceX {
    get { return faceX_; }
    set {
      faceX_ = value;
    }
  }

  /// <summary>Field number for the "face_y" field.</summary>
  public const int FaceYFieldNumber = 4;
  private float faceY_;
  /// <summary>
  /// 미터, 위
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float FaceY {
    get { return faceY_; }
    set {
      faceY_ = value;
    }
  }

  /// <summary>Field number for the "distance" field.</summary>
  public const int DistanceFieldNumber = 5;
  private float distance_;
  /// <summary>
  /// 미터
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Distance {
    get { return distance_; }
    set {
      distance_ = value;
    }
  }

  /// <summary>Field number for the "rank" field.</summary>
  public const int RankFieldNumber = 6;
  private int rank_;
  /// <summary>
  /// 0이 1등
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Rank {
    get { return rank_; }
    set {
      rank_ = value;
    }
  }

  /// <summary>Field number for the "points" field.</summary>
  public const int PointsFieldNumber = 7;
  private int points_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Points {
    get { return points_; }
    set {
      points_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ArcheryRoundPlacementToC);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ArcheryRoundPlacementToC other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ShooterId != other.ShooterId) return false;
    if (Hit != other.Hit) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FaceX, other.FaceX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FaceY, other.FaceY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Distance, other.Distance)) return false;
    if (Rank != other.Rank) return false;
    if (Points != other.Points) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ShooterId.Length != 0) hash ^= ShooterId.GetHashCode();
    if (Hit != false) hash ^= Hit.GetHashCode();
    if (FaceX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FaceX);
    if (FaceY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FaceY);
    if (Distance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Distance);
    if (Rank != 0) hash ^= Rank.GetHashCode();
    if (Points != 0) hash ^= Points.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ShooterId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(ShooterId);
    }
    if (Hit != false) {
      output.WriteRawTag(16);
      output.WriteBool(Hit);
    }
    if (FaceX != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(FaceX);
    }
    if (FaceY != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(FaceY);
    }
    if (Distance != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(Distance);
    }
    if (Rank != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Rank);
    }
    if (Points != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Points);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ShooterId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(ShooterId);
    }
    if (Hit != false) {
      output.WriteRawTag(16);
      output.WriteBool(Hit);
    }
    if (FaceX != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(FaceX);
    }
    if (FaceY != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(FaceY);
    }
    if (Distance != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(Distance);
    }
    if (Rank != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Rank);
    }
    if (Points != 0) {
      output.WriteRawTag(56);
      output.WriteInt32(Points);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ShooterId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ShooterId);
    }
    if (Hit != false) {
      size += 1 + 1;
    }
    if (FaceX != 0F) {
      size += 1 + 4;
    }
    if (FaceY != 0F) {
      size += 1 + 4;
    }
    if (Distance != 0F) {
      size += 1 + 4;
    }
    if (Rank != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rank);
    }
    if (Points != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Points);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ArcheryRoundPlacementToC other) {
    if (other == null) {
      return;
    }
    if (other.ShooterId.Length != 0) {
      ShooterId = other.ShooterId;
    }
    if (other.Hit != false) {
      Hit = other.Hit;
    }
    if (other.FaceX != 0F) {
      FaceX = other.FaceX;
    }
    if (other.FaceY != 0F) {
      FaceY = other.FaceY;
    }
    if (other.Distance != 0F) {
      Distance = other.Distance;
    }
    if (other.Rank != 0) {
      Rank = other.Rank;
    }
    if (other.Points != 0) {
      Points = other.Points;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ShooterId = input.ReadString();
          break;
        }
        case 16: {
          Hit = input.ReadBool();
          break;
        }
        case 29: {
          FaceX = input.ReadFloat();
          break;
        }
        case 37: {
          FaceY = input.ReadFloat();
          break;
        }
        case 45: {
          Distance = input.ReadFloat();
          break;
        }
        case 48: {
          Rank = input.ReadInt32();
          break;
        }
        case 56: {
          Points = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          ShooterId = input.ReadString();
          break;
        }
        case 16: {
          Hit = input.ReadBool();
          break;
        }
        case 29: {
          FaceX = input.ReadFloat();
          break;
        }
        case 37: {
          FaceY = input.ReadFloat();
          break;
        }
        case 45: {
          Distance = input.ReadFloat();
          break;
        }
        case 48: {
          Rank = input.ReadInt32();
          break;
        }
        case 56: {
          Points = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ArcheryRoundResultToC : pb::IMessage<ArcheryRoundResultToC>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ArcheryRoundResultToC> _parser = new pb::MessageParser<ArcheryRoundResultToC>(() => new ArcheryRoundResultToC());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ArcheryRoundResultToC> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ArcheryRoundResultToCReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryRoundResultToC() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryRoundResultToC(ArcheryRoundResultToC other) : this() {
    roundIndex_ = other.roundIndex_;
    multiplier_ = other.multiplier_;
    placements_ = other.placements_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryRoundResultToC Clone() {
    return new ArcheryRoundResultToC(this);
  }

  /// <summary>Field number for the "round_index" field.</summary>
  public const int RoundIndexFieldNumber = 1;
  private int roundIndex_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int RoundIndex {
    get { return roundIndex_; }
    set {
      roundIndex_ = value;
    }
  }

  /// <summary>Field number for the "multiplier" field.</summary>
  public const int MultiplierFieldNumber = 2;
  private int multiplier_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Multiplier {
    get { return multiplier_; }
    set {
      multiplier_ = value;
    }
  }

  /// <summary>Field number for the "placements" field.</summary>
  public const int PlacementsFieldNumber = 3;
  private static readonly pb::FieldCodec<global::ArcheryRoundPlacementToC> _repeated_placements_codec
      = pb::FieldCodec.ForMessage(26, global::ArcheryRoundPlacementToC.Parser);
  private readonly pbc::RepeatedField<global::ArcheryRoundPlacementToC> placements_ = new pbc::RepeatedField<global::ArcheryRoundPlacementToC>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ArcheryRoundPlacementToC> Placements {
    get { return placements_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ArcheryRoundResultToC);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ArcheryRoundResultToC other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RoundIndex != other.RoundIndex) return false;
    if (Multiplier != other.Multiplier) return false;
    if(!placements_.Equals(other.placements_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (RoundIndex != 0) hash ^= RoundIndex.GetHashCode();
    if (Multiplier != 0) hash ^= Multiplier.GetHashCode();
    hash ^= placements_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (RoundIndex != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(RoundIndex);
    }
    if (Multiplier != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Multiplier);
    }
    placements_.WriteTo(output, _repeated_placements_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (RoundIndex != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(RoundIndex);
    }
    if (Multiplier != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Multiplier);
    }
    placements_.WriteTo(ref output, _repeated_placements_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (RoundIndex != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoundIndex);
    }
    if (Multiplier != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Multiplier);
    }
    size += placements_.CalculateSize(_repeated_placements_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ArcheryRoundResultToC other) {
    if (other == null) {
      return;
    }
    if (other.RoundIndex != 0) {
      RoundIndex = other.RoundIndex;
    }
    if (other.Multiplier != 0) {
      Multiplier = other.Multiplier;
    }
    placements_.Add(other.placements_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          RoundIndex = input.ReadInt32();
          break;
        }
        case 16: {
          Multiplier = input.ReadInt32();
          break;
        }
        case 26: {
          placements_.AddEntriesFrom(input, _repeated_placements_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          RoundIndex = input.ReadInt32();
          break;
        }
        case 16: {
          Multiplier = input.ReadInt32();
          break;
        }
        case 26: {
          placements_.AddEntriesFrom(ref input, _repeated_placements_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
