// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ArcheryShotToC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ArcheryShotToC.proto</summary>
public static partial class ArcheryShotToCReflection {

  #region Descriptor
  /// <summary>File descriptor for ArcheryShotToC.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ArcheryShotToCReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRBcmNoZXJ5U2hvdFRvQy5wcm90bxoSUHJvdG9WZWN0b3IzLnByb3RvIncK",
          "DkFyY2hlcnlTaG90VG9DEhIKCnNob290ZXJfaWQYASABKAkSEQoJZmlyZV90",
          "aWNrGAIgASgDEh0KBm9yaWdpbhgDIAEoCzINLlByb3RvVmVjdG9yMxIfCgh2",
          "ZWxvY2l0eRgEIAEoCzINLlByb3RvVmVjdG9yM2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ProtoVector3Reflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ArcheryShotToC), global::ArcheryShotToC.Parser, new[]{ "ShooterId", "FireTick", "Origin", "Velocity" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 폴리모픽 래퍼 안에 담기는 payload — top-level 패킷 아님(@auto_generate 없음).
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ArcheryShotToC : pb::IMessage<ArcheryShotToC>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ArcheryShotToC> _parser = new pb::MessageParser<ArcheryShotToC>(() => new ArcheryShotToC());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ArcheryShotToC> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ArcheryShotToCReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryShotToC() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryShotToC(ArcheryShotToC other) : this() {
    shooterId_ = other.shooterId_;
    fireTick_ = other.fireTick_;
    origin_ = other.origin_ != null ? other.origin_.Clone() : null;
    velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryShotToC Clone() {
    return new ArcheryShotToC(this);
  }

  /// <summary>Field number for the "shooter_id" field.</summary>
  public const int ShooterIdFieldNumber = 1;
  private string shooterId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ShooterId {
    get { return shooterId_; }
    set {
      shooterId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "fire_tick" field.</summary>
  public const int FireTickFieldNumber = 2;
  private long fireTick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long FireTick {
    get { return fireTick_; }
    set {
      fireTick_ = value;
    }
  }

  /// <summary>Field number for the "origin" field.</summary>
  public const int OriginFieldNumber = 3;
  private global::ProtoVector3 origin_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoVector3 Origin {
    get { return origin_; }
    set {
      origin_ = value;
    }
  }

  /// <summary>Field number for the "velocity" field.</summary>
  public const int VelocityFieldNumber = 4;
  private global::ProtoVector3 velocity_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoVector3 Velocity {
    get { return velocity_; }
    set {
      velocity_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ArcheryShotToC);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ArcheryShotToC other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ShooterId != other.ShooterId) return false;
    if (FireTick != other.FireTick) return false;
    if (!object.Equals(Origin, other.Origin)) return false;
    if (!object.Equals(Velocity, other.Velocity)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ShooterId.Length != 0) hash ^= ShooterId.GetHashCode();
    if (FireTick != 0L) hash ^= FireTick.GetHashCode();
    if (origin_ != null) hash ^= Origin.GetHashCode();
    if (velocity_ != null) hash ^= Velocity.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ShooterId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(ShooterId);
    }
    if (FireTick != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(FireTick);
    }
    if (origin_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Origin);
    }
    if (velocity_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Velocity);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ShooterId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(ShooterId);
    }
    if (FireTick != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(FireTick);
    }
    if (origin_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Origin);
    }
    if (velocity_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Velocity);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ShooterId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ShooterId);
    }
    if (FireTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(FireTick);
    }
    if (origin_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Origin);
    }
    if (velocity_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ArcheryShotToC other) {
    if (other == null) {
      return;
    }
    if (other.ShooterId.Length != 0) {
      ShooterId = other.ShooterId;
    }
    if (other.FireTick != 0L) {
      FireTick = other.FireTick;
    }
    if (other.origin_ != null) {
      if (origin_ == null) {
        Origin = new global::ProtoVector3();
      }
      Origin.MergeFrom(other.Origin);
    }
    if (other.velocity_ != null) {
      if (velocity_ == null) {
        Velocity = new global::ProtoVector3();
      }
      Velocity.MergeFrom(other.Velocity);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ShooterId = input.ReadString();
          break;
        }
        case 16: {
          FireTick = input.ReadInt64();
          break;
        }
        case 26: {
          if (origin_ == null) {
            Origin = new global::ProtoVector3();
          }
          input.ReadMessage(Origin);
          break;
        }
        case 34: {
          if (velocity_ == null) {
            Velocity = new global::ProtoVector3();
          }
          input.ReadMessage(Velocity);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          ShooterId = input.ReadString();
          break;
        }
        case 16: {
          FireTick = input.ReadInt64();
          break;
        }
        case 26: {
          if (origin_ == null) {
            Origin = new global::ProtoVector3();
          }
          input.ReadMessage(Origin);
          break;
        }
        case 34: {
          if (velocity_ == null) {
            Velocity = new global::ProtoVector3();
          }
          input.ReadMessage(Velocity);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
