// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ArcheryStateToC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ArcheryStateToC.proto</summary>
public static partial class ArcheryStateToCReflection {

  #region Descriptor
  /// <summary>File descriptor for ArcheryStateToC.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ArcheryStateToCReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVBcmNoZXJ5U3RhdGVUb0MucHJvdG8iPAoPQXJjaGVyeVN0YXRlVG9DEhIK",
          "CndhdmVfaW5kZXgYASABKAUSFQoNY29uc3VtZWRfbWFzaxgCIAEoBWIGcHJv",
          "dG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ArcheryStateToC), global::ArcheryStateToC.Parser, new[]{ "WaveIndex", "ConsumedMask" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 지금 웨이브에서 어느 과녁이 먹혔나(서버 → 클라). 바뀔 때만 reliable로 간다.
/// 과녁이 *뜨는* 것은 양쪽이 씨앗으로 계산하므로 보내지 않는다 — 보내는 것은 "사라진 것"뿐이다.
/// 사건으로 보내면 끊겼다 돌아온 사람이 이미 먹힌 과녁을 살아 있는 것으로 본다(PanchigiStateToC와 같은 사정).
/// @auto_generate
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ArcheryStateToC : pb::IMessage<ArcheryStateToC>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ArcheryStateToC> _parser = new pb::MessageParser<ArcheryStateToC>(() => new ArcheryStateToC());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ArcheryStateToC> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ArcheryStateToCReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryStateToC() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryStateToC(ArcheryStateToC other) : this() {
    waveIndex_ = other.waveIndex_;
    consumedMask_ = other.consumedMask_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ArcheryStateToC Clone() {
    return new ArcheryStateToC(this);
  }

  /// <summary>Field number for the "wave_index" field.</summary>
  public const int WaveIndexFieldNumber = 1;
  private int waveIndex_;
  /// <summary>
  /// 이 마스크가 말하는 웨이브. 받는 쪽이 자기 웨이브와 다르면 버린다(늦게 도착한 낡은 소식).
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WaveIndex {
    get { return waveIndex_; }
    set {
      waveIndex_ = value;
    }
  }

  /// <summary>Field number for the "consumed_mask" field.</summary>
  public const int ConsumedMaskFieldNumber = 2;
  private int consumedMask_;
  /// <summary>
  /// 먹힌 슬롯의 비트마스크 — 슬롯 0이 1비트. 한 웨이브에 과녁이 최대 3개라 세 비트면 족하다.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ConsumedMask {
    get { return consumedMask_; }
    set {
      consumedMask_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ArcheryStateToC);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ArcheryStateToC other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (WaveIndex != other.WaveIndex) return false;
    if (ConsumedMask != other.ConsumedMask) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (WaveIndex != 0) hash ^= WaveIndex.GetHashCode();
    if (ConsumedMask != 0) hash ^= ConsumedMask.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (WaveIndex != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(WaveIndex);
    }
    if (ConsumedMask != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ConsumedMask);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (WaveIndex != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(WaveIndex);
    }
    if (ConsumedMask != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ConsumedMask);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (WaveIndex != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(WaveIndex);
    }
    if (ConsumedMask != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConsumedMask);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ArcheryStateToC other) {
    if (other == null) {
      return;
    }
    if (other.WaveIndex != 0) {
      WaveIndex = other.WaveIndex;
    }
    if (other.ConsumedMask != 0) {
      ConsumedMask = other.ConsumedMask;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          WaveIndex = input.ReadInt32();
          break;
        }
        case 16: {
          ConsumedMask = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          WaveIndex = input.ReadInt32();
          break;
        }
        case 16: {
          ConsumedMask = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
