// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DodgeWire.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from DodgeWire.proto</summary>
public static partial class DodgeWireReflection {

  #region Descriptor
  /// <summary>File descriptor for DodgeWire.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DodgeWireReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9Eb2RnZVdpcmUucHJvdG8iWQoQRG9kZ2VQYXR0ZXJuV2lyZRIKCgJpZBgB",
          "IAEoBRIMCgRraW5kGAIgASgFEhIKCnN0YXJ0X3RpY2sYAyABKAMSDAoEc2Vl",
          "ZBgEIAEoBBIJCgFwGAUgAygCIm0KD0RvZGdlUGxheWVyV2lyZRIRCgllbnRp",
          "dHlfaWQYASABKAkSDQoFbGl2ZXMYAiABKAUSHwoXaW52dWxuZXJhYmxlX3Vu",
          "dGlsX3RpY2sYAyABKAMSFwoPZWxpbWluYXRlZF90aWNrGAQgASgDYgZwcm90",
          "bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::DodgePatternWire), global::DodgePatternWire.Parser, new[]{ "Id", "Kind", "StartTick", "Seed", "P" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DodgePlayerWire), global::DodgePlayerWire.Parser, new[]{ "EntityId", "Lives", "InvulnerableUntilTick", "EliminatedTick" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// DodgeStateToC가 싣는 조각들. @auto_generate가 없다 — 단독으로 보내지 않는다.
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class DodgePatternWire : pb::IMessage<DodgePatternWire>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DodgePatternWire> _parser = new pb::MessageParser<DodgePatternWire>(() => new DodgePatternWire());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DodgePatternWire> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DodgeWireReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DodgePatternWire() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DodgePatternWire(DodgePatternWire other) : this() {
    id_ = other.id_;
    kind_ = other.kind_;
    startTick_ = other.startTick_;
    seed_ = other.seed_;
    p_ = other.p_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DodgePatternWire Clone() {
    return new DodgePatternWire(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private int id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "kind" field.</summary>
  public const int KindFieldNumber = 2;
  private int kind_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Kind {
    get { return kind_; }
    set {
      kind_ = value;
    }
  }

  /// <summary>Field number for the "start_tick" field.</summary>
  public const int StartTickFieldNumber = 3;
  private long startTick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long StartTick {
    get { return startTick_; }
    set {
      startTick_ = value;
    }
  }

  /// <summary>Field number for the "seed" field.</summary>
  public const int SeedFieldNumber = 4;
  private ulong seed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Seed {
    get { return seed_; }
    set {
      seed_ = value;
    }
  }

  /// <summary>Field number for the "p" field.</summary>
  public const int PFieldNumber = 5;
  private static readonly pb::FieldCodec<float> _repeated_p_codec
      = pb::FieldCodec.ForFloat(42);
  private readonly pbc::RepeatedField<float> p_ = new pbc::RepeatedField<float>();
  /// <summary>
  /// DodgePattern.P0..P3 (뜻은 DodgeHazards 머리 표)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> P {
    get { return p_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DodgePatternWire);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DodgePatternWire other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Kind != other.Kind) return false;
    if (StartTick != other.StartTick) return false;
    if (Seed != other.Seed) return false;
    if(!p_.Equals(other.p_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Kind != 0) hash ^= Kind.GetHashCode();
    if (StartTick != 0L) hash ^= StartTick.GetHashCode();
    if (Seed != 0UL) hash ^= Seed.GetHashCode();
    hash ^= p_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Kind != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Kind);
    }
    if (StartTick != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(StartTick);
    }
    if (Seed != 0UL) {
      output.WriteRawTag(32);
      output.WriteUInt64(Seed);
    }
    p_.WriteTo(output, _repeated_p_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Kind != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Kind);
    }
    if (StartTick != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(StartTick);
    }
    if (Seed != 0UL) {
      output.WriteRawTag(32);
      output.WriteUInt64(Seed);
    }
    p_.WriteTo(ref output, _repeated_p_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (Kind != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Kind);
    }
    if (StartTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartTick);
    }
    if (Seed != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Seed);
    }
    size += p_.CalculateSize(_repeated_p_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DodgePatternWire other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Kind != 0) {
      Kind = other.Kind;
    }
    if (other.StartTick != 0L) {
      StartTick = other.StartTick;
    }
    if (other.Seed != 0UL) {
      Seed = other.Seed;
    }
    p_.Add(other.p_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 16: {
          Kind = input.ReadInt32();
          break;
        }
        case 24: {
          StartTick = input.ReadInt64();
          break;
        }
        case 32: {
          Seed = input.ReadUInt64();
          break;
        }
        case 42:
        case 45: {
          p_.AddEntriesFrom(input, _repeated_p_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 16: {
          Kind = input.ReadInt32();
          break;
        }
        case 24: {
          StartTick = input.ReadInt64();
          break;
        }
        case 32: {
          Seed = input.ReadUInt64();
          break;
        }
        case 42:
        case 45: {
          p_.AddEntriesFrom(ref input, _repeated_p_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class DodgePlayerWire : pb::IMessage<DodgePlayerWire>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DodgePlayerWire> _parser = new pb::MessageParser<DodgePlayerWire>(() => new DodgePlayerWire());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DodgePlayerWire> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DodgeWireReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DodgePlayerWire() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DodgePlayerWire(DodgePlayerWire other) : this() {
    entityId_ = other.entityId_;
    lives_ = other.lives_;
    invulnerableUntilTick_ = other.invulnerableUntilTick_;
    eliminatedTick_ = other.eliminatedTick_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DodgePlayerWire Clone() {
    return new DodgePlayerWire(this);
  }

  /// <summary>Field number for the "entity_id" field.</summary>
  public const int EntityIdFieldNumber = 1;
  private string entityId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string EntityId {
    get { return entityId_; }
    set {
      entityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "lives" field.</summary>
  public const int LivesFieldNumber = 2;
  private int lives_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Lives {
    get { return lives_; }
    set {
      lives_ = value;
    }
  }

  /// <summary>Field number for the "invulnerable_until_tick" field.</summary>
  public const int InvulnerableUntilTickFieldNumber = 3;
  private long invulnerableUntilTick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long InvulnerableUntilTick {
    get { return invulnerableUntilTick_; }
    set {
      invulnerableUntilTick_ = value;
    }
  }

  /// <summary>Field number for the "eliminated_tick" field.</summary>
  public const int EliminatedTickFieldNumber = 4;
  private long eliminatedTick_;
  /// <summary>
  /// 탈락 안 했으면 -1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long EliminatedTick {
    get { return eliminatedTick_; }
    set {
      eliminatedTick_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DodgePlayerWire);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DodgePlayerWire other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EntityId != other.EntityId) return false;
    if (Lives != other.Lives) return false;
    if (InvulnerableUntilTick != other.InvulnerableUntilTick) return false;
    if (EliminatedTick != other.EliminatedTick) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EntityId.Length != 0) hash ^= EntityId.GetHashCode();
    if (Lives != 0) hash ^= Lives.GetHashCode();
    if (InvulnerableUntilTick != 0L) hash ^= InvulnerableUntilTick.GetHashCode();
    if (EliminatedTick != 0L) hash ^= EliminatedTick.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EntityId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(EntityId);
    }
    if (Lives != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Lives);
    }
    if (InvulnerableUntilTick != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(InvulnerableUntilTick);
    }
    if (EliminatedTick != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(EliminatedTick);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EntityId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(EntityId);
    }
    if (Lives != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Lives);
    }
    if (InvulnerableUntilTick != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(InvulnerableUntilTick);
    }
    if (EliminatedTick != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(EliminatedTick);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EntityId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityId);
    }
    if (Lives != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Lives);
    }
    if (InvulnerableUntilTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(InvulnerableUntilTick);
    }
    if (EliminatedTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(EliminatedTick);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DodgePlayerWire other) {
    if (other == null) {
      return;
    }
    if (other.EntityId.Length != 0) {
      EntityId = other.EntityId;
    }
    if (other.Lives != 0) {
      Lives = other.Lives;
    }
    if (other.InvulnerableUntilTick != 0L) {
      InvulnerableUntilTick = other.InvulnerableUntilTick;
    }
    if (other.EliminatedTick != 0L) {
      EliminatedTick = other.EliminatedTick;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          EntityId = input.ReadString();
          break;
        }
        case 16: {
          Lives = input.ReadInt32();
          break;
        }
        case 24: {
          InvulnerableUntilTick = input.ReadInt64();
          break;
        }
        case 32: {
          EliminatedTick = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          EntityId = input.ReadString();
          break;
        }
        case 16: {
          Lives = input.ReadInt32();
          break;
        }
        case 24: {
          InvulnerableUntilTick = input.ReadInt64();
          break;
        }
        case 32: {
          EliminatedTick = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
