// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EntitySnap.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from EntitySnap.proto</summary>
public static partial class EntitySnapReflection {

  #region Descriptor
  /// <summary>File descriptor for EntitySnap.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EntitySnapReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBFbnRpdHlTbmFwLnByb3RvGhJQcm90b1ZlY3RvcjMucHJvdG8aHVByb3Rv",
          "TW90aW9uQ29udHJpYnV0aW9uLnByb3RvGhdQcm90b0FjdGl2ZUVmZmVjdC5w",
          "cm90byLFAwoKRW50aXR5U25hcBIRCgllbnRpdHlfaWQYASABKAkSHwoIcG9z",
          "aXRpb24YAiABKAsyDS5Qcm90b1ZlY3RvcjMSHwoIcm90YXRpb24YAyABKAsy",
          "DS5Qcm90b1ZlY3RvcjMSHwoIdmVsb2NpdHkYBCABKAsyDS5Qcm90b1ZlY3Rv",
          "cjMSDgoGbWF4X0hQGAUgASgFEhIKCmN1cnJlbnRfSFAYBiABKAUSNgoUbW90",
          "aW9uX2NvbnRyaWJ1dGlvbnMYByADKAsyGC5Qcm90b01vdGlvbkNvbnRyaWJ1",
          "dGlvbhIQCghncm91bmRlZBgIIAEoCBIZChFhY3RpdmVfYWJpbGl0eV9pZBgJ",
          "IAEoBRIYChBhYmlsaXR5X2VuZF90aWNrGAogASgDEioKDnN0YXR1c19lZmZl",
          "Y3RzGAsgAygLMhIuUHJvdG9BY3RpdmVFZmZlY3QSFQoNc3R1bl9lbmRfdGlj",
          "axgOIAEoAxIXCg9pbnZ1bG5fZW5kX3RpY2sYDyABKAMSFAoMcG9zdHVyZV9h",
          "eGlzGBAgASgCEg8KB2dsaWRpbmcYESABKAgSDwoHc3RhbWluYRgSIAEoAkoE",
          "CAwQDUoECA0QDmIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ProtoVector3Reflection.Descriptor, global::ProtoMotionContributionReflection.Descriptor, global::ProtoActiveEffectReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::EntitySnap), global::EntitySnap.Parser, new[]{ "EntityId", "Position", "Rotation", "Velocity", "MaxHP", "CurrentHP", "MotionContributions", "Grounded", "ActiveAbilityId", "AbilityEndTick", "StatusEffects", "StunEndTick", "InvulnEndTick", "PostureAxis", "Gliding", "Stamina" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EntitySnap : pb::IMessage<EntitySnap>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EntitySnap> _parser = new pb::MessageParser<EntitySnap>(() => new EntitySnap());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EntitySnap> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EntitySnapReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySnap() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySnap(EntitySnap other) : this() {
    entityId_ = other.entityId_;
    position_ = other.position_ != null ? other.position_.Clone() : null;
    rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
    velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
    maxHP_ = other.maxHP_;
    currentHP_ = other.currentHP_;
    motionContributions_ = other.motionContributions_.Clone();
    grounded_ = other.grounded_;
    activeAbilityId_ = other.activeAbilityId_;
    abilityEndTick_ = other.abilityEndTick_;
    statusEffects_ = other.statusEffects_.Clone();
    stunEndTick_ = other.stunEndTick_;
    invulnEndTick_ = other.invulnEndTick_;
    postureAxis_ = other.postureAxis_;
    gliding_ = other.gliding_;
    stamina_ = other.stamina_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySnap Clone() {
    return new EntitySnap(this);
  }

  /// <summary>Field number for the "entity_id" field.</summary>
  public const int EntityIdFieldNumber = 1;
  private string entityId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string EntityId {
    get { return entityId_; }
    set {
      entityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "position" field.</summary>
  public const int PositionFieldNumber = 2;
  private global::ProtoVector3 position_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoVector3 Position {
    get { return position_; }
    set {
      position_ = value;
    }
  }

  /// <summary>Field number for the "rotation" field.</summary>
  public const int RotationFieldNumber = 3;
  private global::ProtoVector3 rotation_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoVector3 Rotation {
    get { return rotation_; }
    set {
      rotation_ = value;
    }
  }

  /// <summary>Field number for the "velocity" field.</summary>
  public const int VelocityFieldNumber = 4;
  private global::ProtoVector3 velocity_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoVector3 Velocity {
    get { return velocity_; }
    set {
      velocity_ = value;
    }
  }

  /// <summary>Field number for the "max_HP" field.</summary>
  public const int MaxHPFieldNumber = 5;
  private int maxHP_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MaxHP {
    get { return maxHP_; }
    set {
      maxHP_ = value;
    }
  }

  /// <summary>Field number for the "current_HP" field.</summary>
  public const int CurrentHPFieldNumber = 6;
  private int currentHP_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CurrentHP {
    get { return currentHP_; }
    set {
      currentHP_ = value;
    }
  }

  /// <summary>Field number for the "motion_contributions" field.</summary>
  public const int MotionContributionsFieldNumber = 7;
  private static readonly pb::FieldCodec<global::ProtoMotionContribution> _repeated_motionContributions_codec
      = pb::FieldCodec.ForMessage(58, global::ProtoMotionContribution.Parser);
  private readonly pbc::RepeatedField<global::ProtoMotionContribution> motionContributions_ = new pbc::RepeatedField<global::ProtoMotionContribution>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ProtoMotionContribution> MotionContributions {
    get { return motionContributions_; }
  }

  /// <summary>Field number for the "grounded" field.</summary>
  public const int GroundedFieldNumber = 8;
  private bool grounded_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Grounded {
    get { return grounded_; }
    set {
      grounded_ = value;
    }
  }

  /// <summary>Field number for the "active_ability_id" field.</summary>
  public const int ActiveAbilityIdFieldNumber = 9;
  private int activeAbilityId_;
  /// <summary>
  /// 0 = 시전 중 아님
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ActiveAbilityId {
    get { return activeAbilityId_; }
    set {
      activeAbilityId_ = value;
    }
  }

  /// <summary>Field number for the "ability_end_tick" field.</summary>
  public const int AbilityEndTickFieldNumber = 10;
  private long abilityEndTick_;
  /// <summary>
  /// 시전이 끝나는 절대 틱(= RecoveryEndTick)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long AbilityEndTick {
    get { return abilityEndTick_; }
    set {
      abilityEndTick_ = value;
    }
  }

  /// <summary>Field number for the "status_effects" field.</summary>
  public const int StatusEffectsFieldNumber = 11;
  private static readonly pb::FieldCodec<global::ProtoActiveEffect> _repeated_statusEffects_codec
      = pb::FieldCodec.ForMessage(90, global::ProtoActiveEffect.Parser);
  private readonly pbc::RepeatedField<global::ProtoActiveEffect> statusEffects_ = new pbc::RepeatedField<global::ProtoActiveEffect>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ProtoActiveEffect> StatusEffects {
    get { return statusEffects_; }
  }

  /// <summary>Field number for the "stun_end_tick" field.</summary>
  public const int StunEndTickFieldNumber = 14;
  private long stunEndTick_;
  /// <summary>
  /// Flappy: 멈춤이 풀리는 절대 틱. 0 = 안 멈춤
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long StunEndTick {
    get { return stunEndTick_; }
    set {
      stunEndTick_ = value;
    }
  }

  /// <summary>Field number for the "invuln_end_tick" field.</summary>
  public const int InvulnEndTickFieldNumber = 15;
  private long invulnEndTick_;
  /// <summary>
  /// Flappy: 다시 안 걸리는 구간이 끝나는 절대 틱. 0 = 아님
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long InvulnEndTick {
    get { return invulnEndTick_; }
    set {
      invulnEndTick_ = value;
    }
  }

  /// <summary>Field number for the "posture_axis" field.</summary>
  public const int PostureAxisFieldNumber = 16;
  private float postureAxis_;
  /// <summary>
  /// Skydive: 0 = 대자, 1 = 다이브
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float PostureAxis {
    get { return postureAxis_; }
    set {
      postureAxis_ = value;
    }
  }

  /// <summary>Field number for the "gliding" field.</summary>
  public const int GlidingFieldNumber = 17;
  private bool gliding_;
  /// <summary>
  /// Skydive: 패러세일을 폈나
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Gliding {
    get { return gliding_; }
    set {
      gliding_ = value;
    }
  }

  /// <summary>Field number for the "stamina" field.</summary>
  public const int StaminaFieldNumber = 18;
  private float stamina_;
  /// <summary>
  /// Skydive: 남은 활공 자원
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Stamina {
    get { return stamina_; }
    set {
      stamina_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EntitySnap);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EntitySnap other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EntityId != other.EntityId) return false;
    if (!object.Equals(Position, other.Position)) return false;
    if (!object.Equals(Rotation, other.Rotation)) return false;
    if (!object.Equals(Velocity, other.Velocity)) return false;
    if (MaxHP != other.MaxHP) return false;
    if (CurrentHP != other.CurrentHP) return false;
    if(!motionContributions_.Equals(other.motionContributions_)) return false;
    if (Grounded != other.Grounded) return false;
    if (ActiveAbilityId != other.ActiveAbilityId) return false;
    if (AbilityEndTick != other.AbilityEndTick) return false;
    if(!statusEffects_.Equals(other.statusEffects_)) return false;
    if (StunEndTick != other.StunEndTick) return false;
    if (InvulnEndTick != other.InvulnEndTick) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PostureAxis, other.PostureAxis)) return false;
    if (Gliding != other.Gliding) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Stamina, other.Stamina)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EntityId.Length != 0) hash ^= EntityId.GetHashCode();
    if (position_ != null) hash ^= Position.GetHashCode();
    if (rotation_ != null) hash ^= Rotation.GetHashCode();
    if (velocity_ != null) hash ^= Velocity.GetHashCode();
    if (MaxHP != 0) hash ^= MaxHP.GetHashCode();
    if (CurrentHP != 0) hash ^= CurrentHP.GetHashCode();
    hash ^= motionContributions_.GetHashCode();
    if (Grounded != false) hash ^= Grounded.GetHashCode();
    if (ActiveAbilityId != 0) hash ^= ActiveAbilityId.GetHashCode();
    if (AbilityEndTick != 0L) hash ^= AbilityEndTick.GetHashCode();
    hash ^= statusEffects_.GetHashCode();
    if (StunEndTick != 0L) hash ^= StunEndTick.GetHashCode();
    if (InvulnEndTick != 0L) hash ^= InvulnEndTick.GetHashCode();
    if (PostureAxis != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PostureAxis);
    if (Gliding != false) hash ^= Gliding.GetHashCode();
    if (Stamina != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Stamina);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EntityId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(EntityId);
    }
    if (position_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Position);
    }
    if (rotation_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Rotation);
    }
    if (velocity_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Velocity);
    }
    if (MaxHP != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(MaxHP);
    }
    if (CurrentHP != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(CurrentHP);
    }
    motionContributions_.WriteTo(output, _repeated_motionContributions_codec);
    if (Grounded != false) {
      output.WriteRawTag(64);
      output.WriteBool(Grounded);
    }
    if (ActiveAbilityId != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(ActiveAbilityId);
    }
    if (AbilityEndTick != 0L) {
      output.WriteRawTag(80);
      output.WriteInt64(AbilityEndTick);
    }
    statusEffects_.WriteTo(output, _repeated_statusEffects_codec);
    if (StunEndTick != 0L) {
      output.WriteRawTag(112);
      output.WriteInt64(StunEndTick);
    }
    if (InvulnEndTick != 0L) {
      output.WriteRawTag(120);
      output.WriteInt64(InvulnEndTick);
    }
    if (PostureAxis != 0F) {
      output.WriteRawTag(133, 1);
      output.WriteFloat(PostureAxis);
    }
    if (Gliding != false) {
      output.WriteRawTag(136, 1);
      output.WriteBool(Gliding);
    }
    if (Stamina != 0F) {
      output.WriteRawTag(149, 1);
      output.WriteFloat(Stamina);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EntityId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(EntityId);
    }
    if (position_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Position);
    }
    if (rotation_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Rotation);
    }
    if (velocity_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Velocity);
    }
    if (MaxHP != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(MaxHP);
    }
    if (CurrentHP != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(CurrentHP);
    }
    motionContributions_.WriteTo(ref output, _repeated_motionContributions_codec);
    if (Grounded != false) {
      output.WriteRawTag(64);
      output.WriteBool(Grounded);
    }
    if (ActiveAbilityId != 0) {
      output.WriteRawTag(72);
      output.WriteInt32(ActiveAbilityId);
    }
    if (AbilityEndTick != 0L) {
      output.WriteRawTag(80);
      output.WriteInt64(AbilityEndTick);
    }
    statusEffects_.WriteTo(ref output, _repeated_statusEffects_codec);
    if (StunEndTick != 0L) {
      output.WriteRawTag(112);
      output.WriteInt64(StunEndTick);
    }
    if (InvulnEndTick != 0L) {
      output.WriteRawTag(120);
      output.WriteInt64(InvulnEndTick);
    }
    if (PostureAxis != 0F) {
      output.WriteRawTag(133, 1);
      output.WriteFloat(PostureAxis);
    }
    if (Gliding != false) {
      output.WriteRawTag(136, 1);
      output.WriteBool(Gliding);
    }
    if (Stamina != 0F) {
      output.WriteRawTag(149, 1);
      output.WriteFloat(Stamina);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EntityId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityId);
    }
    if (position_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
    }
    if (rotation_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
    }
    if (velocity_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
    }
    if (MaxHP != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxHP);
    }
    if (CurrentHP != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentHP);
    }
    size += motionContributions_.CalculateSize(_repeated_motionContributions_codec);
    if (Grounded != false) {
      size += 1 + 1;
    }
    if (ActiveAbilityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ActiveAbilityId);
    }
    if (AbilityEndTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(AbilityEndTick);
    }
    size += statusEffects_.CalculateSize(_repeated_statusEffects_codec);
    if (StunEndTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(StunEndTick);
    }
    if (InvulnEndTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(InvulnEndTick);
    }
    if (PostureAxis != 0F) {
      size += 2 + 4;
    }
    if (Gliding != false) {
      size += 2 + 1;
    }
    if (Stamina != 0F) {
      size += 2 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EntitySnap other) {
    if (other == null) {
      return;
    }
    if (other.EntityId.Length != 0) {
      EntityId = other.EntityId;
    }
    if (other.position_ != null) {
      if (position_ == null) {
        Position = new global::ProtoVector3();
      }
      Position.MergeFrom(other.Position);
    }
    if (other.rotation_ != null) {
      if (rotation_ == null) {
        Rotation = new global::ProtoVector3();
      }
      Rotation.MergeFrom(other.Rotation);
    }
    if (other.velocity_ != null) {
      if (velocity_ == null) {
        Velocity = new global::ProtoVector3();
      }
      Velocity.MergeFrom(other.Velocity);
    }
    if (other.MaxHP != 0) {
      MaxHP = other.MaxHP;
    }
    if (other.CurrentHP != 0) {
      CurrentHP = other.CurrentHP;
    }
    motionContributions_.Add(other.motionContributions_);
    if (other.Grounded != false) {
      Grounded = other.Grounded;
    }
    if (other.ActiveAbilityId != 0) {
      ActiveAbilityId = other.ActiveAbilityId;
    }
    if (other.AbilityEndTick != 0L) {
      AbilityEndTick = other.AbilityEndTick;
    }
    statusEffects_.Add(other.statusEffects_);
    if (other.StunEndTick != 0L) {
      StunEndTick = other.StunEndTick;
    }
    if (other.InvulnEndTick != 0L) {
      InvulnEndTick = other.InvulnEndTick;
    }
    if (other.PostureAxis != 0F) {
      PostureAxis = other.PostureAxis;
    }
    if (other.Gliding != false) {
      Gliding = other.Gliding;
    }
    if (other.Stamina != 0F) {
      Stamina = other.Stamina;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          EntityId = input.ReadString();
          break;
        }
        case 18: {
          if (position_ == null) {
            Position = new global::ProtoVector3();
          }
          input.ReadMessage(Position);
          break;
        }
        case 26: {
          if (rotation_ == null) {
            Rotation = new global::ProtoVector3();
          }
          input.ReadMessage(Rotation);
          break;
        }
        case 34: {
          if (velocity_ == null) {
            Velocity = new global::ProtoVector3();
          }
          input.ReadMessage(Velocity);
          break;
        }
        case 40: {
          MaxHP = input.ReadInt32();
          break;
        }
        case 48: {
          CurrentHP = input.ReadInt32();
          break;
        }
        case 58: {
          motionContributions_.AddEntriesFrom(input, _repeated_motionContributions_codec);
          break;
        }
        case 64: {
          Grounded = input.ReadBool();
          break;
        }
        case 72: {
          ActiveAbilityId = input.ReadInt32();
          break;
        }
        case 80: {
          AbilityEndTick = input.ReadInt64();
          break;
        }
        case 90: {
          statusEffects_.AddEntriesFrom(input, _repeated_statusEffects_codec);
          break;
        }
        case 112: {
          StunEndTick = input.ReadInt64();
          break;
        }
        case 120: {
          InvulnEndTick = input.ReadInt64();
          break;
        }
        case 133: {
          PostureAxis = input.ReadFloat();
          break;
        }
        case 136: {
          Gliding = input.ReadBool();
          break;
        }
        case 149: {
          Stamina = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          EntityId = input.ReadString();
          break;
        }
        case 18: {
          if (position_ == null) {
            Position = new global::ProtoVector3();
          }
          input.ReadMessage(Position);
          break;
        }
        case 26: {
          if (rotation_ == null) {
            Rotation = new global::ProtoVector3();
          }
          input.ReadMessage(Rotation);
          break;
        }
        case 34: {
          if (velocity_ == null) {
            Velocity = new global::ProtoVector3();
          }
          input.ReadMessage(Velocity);
          break;
        }
        case 40: {
          MaxHP = input.ReadInt32();
          break;
        }
        case 48: {
          CurrentHP = input.ReadInt32();
          break;
        }
        case 58: {
          motionContributions_.AddEntriesFrom(ref input, _repeated_motionContributions_codec);
          break;
        }
        case 64: {
          Grounded = input.ReadBool();
          break;
        }
        case 72: {
          ActiveAbilityId = input.ReadInt32();
          break;
        }
        case 80: {
          AbilityEndTick = input.ReadInt64();
          break;
        }
        case 90: {
          statusEffects_.AddEntriesFrom(ref input, _repeated_statusEffects_codec);
          break;
        }
        case 112: {
          StunEndTick = input.ReadInt64();
          break;
        }
        case 120: {
          InvulnEndTick = input.ReadInt64();
          break;
        }
        case 133: {
          PostureAxis = input.ReadFloat();
          break;
        }
        case 136: {
          Gliding = input.ReadBool();
          break;
        }
        case 149: {
          Stamina = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
