// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EntitySnap.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from EntitySnap.proto</summary>
public static partial class EntitySnapReflection {

  #region Descriptor
  /// <summary>File descriptor for EntitySnap.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EntitySnapReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBFbnRpdHlTbmFwLnByb3RvGhJQcm90b1ZlY3RvcjMucHJvdG8aHVByb3Rv",
          "TW90aW9uQ29udHJpYnV0aW9uLnByb3RvIt4BCgpFbnRpdHlTbmFwEhEKCWVu",
          "dGl0eV9pZBgBIAEoCRIfCghwb3NpdGlvbhgCIAEoCzINLlByb3RvVmVjdG9y",
          "MxIfCghyb3RhdGlvbhgDIAEoCzINLlByb3RvVmVjdG9yMxIfCgh2ZWxvY2l0",
          "eRgEIAEoCzINLlByb3RvVmVjdG9yMxIOCgZtYXhfSFAYBSABKAUSEgoKY3Vy",
          "cmVudF9IUBgGIAEoBRI2ChRtb3Rpb25fY29udHJpYnV0aW9ucxgHIAMoCzIY",
          "LlByb3RvTW90aW9uQ29udHJpYnV0aW9uYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ProtoVector3Reflection.Descriptor, global::ProtoMotionContributionReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::EntitySnap), global::EntitySnap.Parser, new[]{ "EntityId", "Position", "Rotation", "Velocity", "MaxHP", "CurrentHP", "MotionContributions" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class EntitySnap : pb::IMessage<EntitySnap>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EntitySnap> _parser = new pb::MessageParser<EntitySnap>(() => new EntitySnap());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EntitySnap> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EntitySnapReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySnap() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySnap(EntitySnap other) : this() {
    entityId_ = other.entityId_;
    position_ = other.position_ != null ? other.position_.Clone() : null;
    rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
    velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
    maxHP_ = other.maxHP_;
    currentHP_ = other.currentHP_;
    motionContributions_ = other.motionContributions_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EntitySnap Clone() {
    return new EntitySnap(this);
  }

  /// <summary>Field number for the "entity_id" field.</summary>
  public const int EntityIdFieldNumber = 1;
  private string entityId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string EntityId {
    get { return entityId_; }
    set {
      entityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "position" field.</summary>
  public const int PositionFieldNumber = 2;
  private global::ProtoVector3 position_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoVector3 Position {
    get { return position_; }
    set {
      position_ = value;
    }
  }

  /// <summary>Field number for the "rotation" field.</summary>
  public const int RotationFieldNumber = 3;
  private global::ProtoVector3 rotation_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoVector3 Rotation {
    get { return rotation_; }
    set {
      rotation_ = value;
    }
  }

  /// <summary>Field number for the "velocity" field.</summary>
  public const int VelocityFieldNumber = 4;
  private global::ProtoVector3 velocity_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoVector3 Velocity {
    get { return velocity_; }
    set {
      velocity_ = value;
    }
  }

  /// <summary>Field number for the "max_HP" field.</summary>
  public const int MaxHPFieldNumber = 5;
  private int maxHP_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MaxHP {
    get { return maxHP_; }
    set {
      maxHP_ = value;
    }
  }

  /// <summary>Field number for the "current_HP" field.</summary>
  public const int CurrentHPFieldNumber = 6;
  private int currentHP_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CurrentHP {
    get { return currentHP_; }
    set {
      currentHP_ = value;
    }
  }

  /// <summary>Field number for the "motion_contributions" field.</summary>
  public const int MotionContributionsFieldNumber = 7;
  private static readonly pb::FieldCodec<global::ProtoMotionContribution> _repeated_motionContributions_codec
      = pb::FieldCodec.ForMessage(58, global::ProtoMotionContribution.Parser);
  private readonly pbc::RepeatedField<global::ProtoMotionContribution> motionContributions_ = new pbc::RepeatedField<global::ProtoMotionContribution>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ProtoMotionContribution> MotionContributions {
    get { return motionContributions_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EntitySnap);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EntitySnap other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EntityId != other.EntityId) return false;
    if (!object.Equals(Position, other.Position)) return false;
    if (!object.Equals(Rotation, other.Rotation)) return false;
    if (!object.Equals(Velocity, other.Velocity)) return false;
    if (MaxHP != other.MaxHP) return false;
    if (CurrentHP != other.CurrentHP) return false;
    if(!motionContributions_.Equals(other.motionContributions_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EntityId.Length != 0) hash ^= EntityId.GetHashCode();
    if (position_ != null) hash ^= Position.GetHashCode();
    if (rotation_ != null) hash ^= Rotation.GetHashCode();
    if (velocity_ != null) hash ^= Velocity.GetHashCode();
    if (MaxHP != 0) hash ^= MaxHP.GetHashCode();
    if (CurrentHP != 0) hash ^= CurrentHP.GetHashCode();
    hash ^= motionContributions_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EntityId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(EntityId);
    }
    if (position_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Position);
    }
    if (rotation_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Rotation);
    }
    if (velocity_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Velocity);
    }
    if (MaxHP != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(MaxHP);
    }
    if (CurrentHP != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(CurrentHP);
    }
    motionContributions_.WriteTo(output, _repeated_motionContributions_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EntityId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(EntityId);
    }
    if (position_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Position);
    }
    if (rotation_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Rotation);
    }
    if (velocity_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Velocity);
    }
    if (MaxHP != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(MaxHP);
    }
    if (CurrentHP != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(CurrentHP);
    }
    motionContributions_.WriteTo(ref output, _repeated_motionContributions_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EntityId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityId);
    }
    if (position_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
    }
    if (rotation_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
    }
    if (velocity_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
    }
    if (MaxHP != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxHP);
    }
    if (CurrentHP != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentHP);
    }
    size += motionContributions_.CalculateSize(_repeated_motionContributions_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EntitySnap other) {
    if (other == null) {
      return;
    }
    if (other.EntityId.Length != 0) {
      EntityId = other.EntityId;
    }
    if (other.position_ != null) {
      if (position_ == null) {
        Position = new global::ProtoVector3();
      }
      Position.MergeFrom(other.Position);
    }
    if (other.rotation_ != null) {
      if (rotation_ == null) {
        Rotation = new global::ProtoVector3();
      }
      Rotation.MergeFrom(other.Rotation);
    }
    if (other.velocity_ != null) {
      if (velocity_ == null) {
        Velocity = new global::ProtoVector3();
      }
      Velocity.MergeFrom(other.Velocity);
    }
    if (other.MaxHP != 0) {
      MaxHP = other.MaxHP;
    }
    if (other.CurrentHP != 0) {
      CurrentHP = other.CurrentHP;
    }
    motionContributions_.Add(other.motionContributions_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          EntityId = input.ReadString();
          break;
        }
        case 18: {
          if (position_ == null) {
            Position = new global::ProtoVector3();
          }
          input.ReadMessage(Position);
          break;
        }
        case 26: {
          if (rotation_ == null) {
            Rotation = new global::ProtoVector3();
          }
          input.ReadMessage(Rotation);
          break;
        }
        case 34: {
          if (velocity_ == null) {
            Velocity = new global::ProtoVector3();
          }
          input.ReadMessage(Velocity);
          break;
        }
        case 40: {
          MaxHP = input.ReadInt32();
          break;
        }
        case 48: {
          CurrentHP = input.ReadInt32();
          break;
        }
        case 58: {
          motionContributions_.AddEntriesFrom(input, _repeated_motionContributions_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          EntityId = input.ReadString();
          break;
        }
        case 18: {
          if (position_ == null) {
            Position = new global::ProtoVector3();
          }
          input.ReadMessage(Position);
          break;
        }
        case 26: {
          if (rotation_ == null) {
            Rotation = new global::ProtoVector3();
          }
          input.ReadMessage(Rotation);
          break;
        }
        case 34: {
          if (velocity_ == null) {
            Velocity = new global::ProtoVector3();
          }
          input.ReadMessage(Velocity);
          break;
        }
        case 40: {
          MaxHP = input.ReadInt32();
          break;
        }
        case 48: {
          CurrentHP = input.ReadInt32();
          break;
        }
        case 58: {
          motionContributions_.AddEntriesFrom(ref input, _repeated_motionContributions_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
