// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InputCommand.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from InputCommand.proto</summary>
public static partial class InputCommandReflection {

  #region Descriptor
  /// <summary>File descriptor for InputCommand.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static InputCommandReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJJbnB1dENvbW1hbmQucHJvdG8inwEKDElucHV0Q29tbWFuZBIXCg9zZXF1",
          "ZW5jZV9udW1iZXIYASABKAMSEgoKaG9yaXpvbnRhbBgCIAEoAhIQCgh2ZXJ0",
          "aWNhbBgDIAEoAhIMCgRqdW1wGAQgASgIEhIKCmFiaWxpdHlfaWQYBiABKAUS",
          "DwoHcG9zdHVyZRgHIAEoAhINCgVnbGlkZRgIIAEoCBIOCgZwb3NpbmcYCSAB",
          "KAhiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::InputCommand), global::InputCommand.Parser, new[]{ "SequenceNumber", "Horizontal", "Vertical", "Jump", "AbilityId", "Posture", "Glide", "Posing" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class InputCommand : pb::IMessage<InputCommand>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<InputCommand> _parser = new pb::MessageParser<InputCommand>(() => new InputCommand());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<InputCommand> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InputCommandReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputCommand() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputCommand(InputCommand other) : this() {
    sequenceNumber_ = other.sequenceNumber_;
    horizontal_ = other.horizontal_;
    vertical_ = other.vertical_;
    jump_ = other.jump_;
    abilityId_ = other.abilityId_;
    posture_ = other.posture_;
    glide_ = other.glide_;
    posing_ = other.posing_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputCommand Clone() {
    return new InputCommand(this);
  }

  /// <summary>Field number for the "sequence_number" field.</summary>
  public const int SequenceNumberFieldNumber = 1;
  private long sequenceNumber_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long SequenceNumber {
    get { return sequenceNumber_; }
    set {
      sequenceNumber_ = value;
    }
  }

  /// <summary>Field number for the "horizontal" field.</summary>
  public const int HorizontalFieldNumber = 2;
  private float horizontal_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Horizontal {
    get { return horizontal_; }
    set {
      horizontal_ = value;
    }
  }

  /// <summary>Field number for the "vertical" field.</summary>
  public const int VerticalFieldNumber = 3;
  private float vertical_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Vertical {
    get { return vertical_; }
    set {
      vertical_ = value;
    }
  }

  /// <summary>Field number for the "jump" field.</summary>
  public const int JumpFieldNumber = 4;
  private bool jump_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Jump {
    get { return jump_; }
    set {
      jump_ = value;
    }
  }

  /// <summary>Field number for the "ability_id" field.</summary>
  public const int AbilityIdFieldNumber = 6;
  private int abilityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int AbilityId {
    get { return abilityId_; }
    set {
      abilityId_ = value;
    }
  }

  /// <summary>Field number for the "posture" field.</summary>
  public const int PostureFieldNumber = 7;
  private float posture_;
  /// <summary>
  /// 자세 축 — 0이면 대자, 1이면 다이브. 사이는 연속이다.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Posture {
    get { return posture_; }
    set {
      posture_ = value;
    }
  }

  /// <summary>Field number for the "glide" field.</summary>
  public const int GlideFieldNumber = 8;
  private bool glide_;
  /// <summary>
  /// 패러세일을 펴고 있나. 자세 축과 무관한 별개 도구다.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Glide {
    get { return glide_; }
    set {
      glide_ = value;
    }
  }

  /// <summary>Field number for the "posing" field.</summary>
  public const int PosingFieldNumber = 9;
  private bool posing_;
  /// <summary>
  /// 자세 슬라이더를 잡고 있나. 자세 값(posture/glide)만으로는 "안 잡음"과
  /// "잡았는데 대자"를 구분할 수 없어서 따로 싣는다 — 그 구분이 스카이다이빙 진입 조건이다.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Posing {
    get { return posing_; }
    set {
      posing_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as InputCommand);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(InputCommand other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SequenceNumber != other.SequenceNumber) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Horizontal, other.Horizontal)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Vertical, other.Vertical)) return false;
    if (Jump != other.Jump) return false;
    if (AbilityId != other.AbilityId) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Posture, other.Posture)) return false;
    if (Glide != other.Glide) return false;
    if (Posing != other.Posing) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SequenceNumber != 0L) hash ^= SequenceNumber.GetHashCode();
    if (Horizontal != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Horizontal);
    if (Vertical != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Vertical);
    if (Jump != false) hash ^= Jump.GetHashCode();
    if (AbilityId != 0) hash ^= AbilityId.GetHashCode();
    if (Posture != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Posture);
    if (Glide != false) hash ^= Glide.GetHashCode();
    if (Posing != false) hash ^= Posing.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SequenceNumber != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(SequenceNumber);
    }
    if (Horizontal != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Horizontal);
    }
    if (Vertical != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(Vertical);
    }
    if (Jump != false) {
      output.WriteRawTag(32);
      output.WriteBool(Jump);
    }
    if (AbilityId != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(AbilityId);
    }
    if (Posture != 0F) {
      output.WriteRawTag(61);
      output.WriteFloat(Posture);
    }
    if (Glide != false) {
      output.WriteRawTag(64);
      output.WriteBool(Glide);
    }
    if (Posing != false) {
      output.WriteRawTag(72);
      output.WriteBool(Posing);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SequenceNumber != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(SequenceNumber);
    }
    if (Horizontal != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Horizontal);
    }
    if (Vertical != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(Vertical);
    }
    if (Jump != false) {
      output.WriteRawTag(32);
      output.WriteBool(Jump);
    }
    if (AbilityId != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(AbilityId);
    }
    if (Posture != 0F) {
      output.WriteRawTag(61);
      output.WriteFloat(Posture);
    }
    if (Glide != false) {
      output.WriteRawTag(64);
      output.WriteBool(Glide);
    }
    if (Posing != false) {
      output.WriteRawTag(72);
      output.WriteBool(Posing);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SequenceNumber != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(SequenceNumber);
    }
    if (Horizontal != 0F) {
      size += 1 + 4;
    }
    if (Vertical != 0F) {
      size += 1 + 4;
    }
    if (Jump != false) {
      size += 1 + 1;
    }
    if (AbilityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(AbilityId);
    }
    if (Posture != 0F) {
      size += 1 + 4;
    }
    if (Glide != false) {
      size += 1 + 1;
    }
    if (Posing != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(InputCommand other) {
    if (other == null) {
      return;
    }
    if (other.SequenceNumber != 0L) {
      SequenceNumber = other.SequenceNumber;
    }
    if (other.Horizontal != 0F) {
      Horizontal = other.Horizontal;
    }
    if (other.Vertical != 0F) {
      Vertical = other.Vertical;
    }
    if (other.Jump != false) {
      Jump = other.Jump;
    }
    if (other.AbilityId != 0) {
      AbilityId = other.AbilityId;
    }
    if (other.Posture != 0F) {
      Posture = other.Posture;
    }
    if (other.Glide != false) {
      Glide = other.Glide;
    }
    if (other.Posing != false) {
      Posing = other.Posing;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SequenceNumber = input.ReadInt64();
          break;
        }
        case 21: {
          Horizontal = input.ReadFloat();
          break;
        }
        case 29: {
          Vertical = input.ReadFloat();
          break;
        }
        case 32: {
          Jump = input.ReadBool();
          break;
        }
        case 48: {
          AbilityId = input.ReadInt32();
          break;
        }
        case 61: {
          Posture = input.ReadFloat();
          break;
        }
        case 64: {
          Glide = input.ReadBool();
          break;
        }
        case 72: {
          Posing = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          SequenceNumber = input.ReadInt64();
          break;
        }
        case 21: {
          Horizontal = input.ReadFloat();
          break;
        }
        case 29: {
          Vertical = input.ReadFloat();
          break;
        }
        case 32: {
          Jump = input.ReadBool();
          break;
        }
        case 48: {
          AbilityId = input.ReadInt32();
          break;
        }
        case 61: {
          Posture = input.ReadFloat();
          break;
        }
        case 64: {
          Glide = input.ReadBool();
          break;
        }
        case 72: {
          Posing = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
