// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InputTimingToC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from InputTimingToC.proto</summary>
public static partial class InputTimingToCReflection {

  #region Descriptor
  /// <summary>File descriptor for InputTimingToC.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static InputTimingToCReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRJbnB1dFRpbWluZ1RvQy5wcm90byJwCg5JbnB1dFRpbWluZ1RvQxINCgVh",
          "dmdfZBgBIAEoARINCgVtYXhfZBgCIAEoBRITCgtwcnVuZV9jb3VudBgDIAEo",
          "BRIVCg1zZXFfZ2FwX2NvdW50GAQgASgFEhQKDHNhbXBsZV9jb3VudBgFIAEo",
          "BWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::InputTimingToC), global::InputTimingToC.Parser, new[]{ "AvgD", "MaxD", "PruneCount", "SeqGapCount", "SampleCount" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// @auto_generate
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class InputTimingToC : pb::IMessage<InputTimingToC>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<InputTimingToC> _parser = new pb::MessageParser<InputTimingToC>(() => new InputTimingToC());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<InputTimingToC> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InputTimingToCReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputTimingToC() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputTimingToC(InputTimingToC other) : this() {
    avgD_ = other.avgD_;
    maxD_ = other.maxD_;
    pruneCount_ = other.pruneCount_;
    seqGapCount_ = other.seqGapCount_;
    sampleCount_ = other.sampleCount_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputTimingToC Clone() {
    return new InputTimingToC(this);
  }

  /// <summary>Field number for the "avg_d" field.</summary>
  public const int AvgDFieldNumber = 1;
  private double avgD_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double AvgD {
    get { return avgD_; }
    set {
      avgD_ = value;
    }
  }

  /// <summary>Field number for the "max_d" field.</summary>
  public const int MaxDFieldNumber = 2;
  private int maxD_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int MaxD {
    get { return maxD_; }
    set {
      maxD_ = value;
    }
  }

  /// <summary>Field number for the "prune_count" field.</summary>
  public const int PruneCountFieldNumber = 3;
  private int pruneCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PruneCount {
    get { return pruneCount_; }
    set {
      pruneCount_ = value;
    }
  }

  /// <summary>Field number for the "seq_gap_count" field.</summary>
  public const int SeqGapCountFieldNumber = 4;
  private int seqGapCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SeqGapCount {
    get { return seqGapCount_; }
    set {
      seqGapCount_ = value;
    }
  }

  /// <summary>Field number for the "sample_count" field.</summary>
  public const int SampleCountFieldNumber = 5;
  private int sampleCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SampleCount {
    get { return sampleCount_; }
    set {
      sampleCount_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as InputTimingToC);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(InputTimingToC other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(AvgD, other.AvgD)) return false;
    if (MaxD != other.MaxD) return false;
    if (PruneCount != other.PruneCount) return false;
    if (SeqGapCount != other.SeqGapCount) return false;
    if (SampleCount != other.SampleCount) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (AvgD != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(AvgD);
    if (MaxD != 0) hash ^= MaxD.GetHashCode();
    if (PruneCount != 0) hash ^= PruneCount.GetHashCode();
    if (SeqGapCount != 0) hash ^= SeqGapCount.GetHashCode();
    if (SampleCount != 0) hash ^= SampleCount.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (AvgD != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(AvgD);
    }
    if (MaxD != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(MaxD);
    }
    if (PruneCount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PruneCount);
    }
    if (SeqGapCount != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(SeqGapCount);
    }
    if (SampleCount != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(SampleCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (AvgD != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(AvgD);
    }
    if (MaxD != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(MaxD);
    }
    if (PruneCount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(PruneCount);
    }
    if (SeqGapCount != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(SeqGapCount);
    }
    if (SampleCount != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(SampleCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (AvgD != 0D) {
      size += 1 + 8;
    }
    if (MaxD != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxD);
    }
    if (PruneCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PruneCount);
    }
    if (SeqGapCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeqGapCount);
    }
    if (SampleCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(SampleCount);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(InputTimingToC other) {
    if (other == null) {
      return;
    }
    if (other.AvgD != 0D) {
      AvgD = other.AvgD;
    }
    if (other.MaxD != 0) {
      MaxD = other.MaxD;
    }
    if (other.PruneCount != 0) {
      PruneCount = other.PruneCount;
    }
    if (other.SeqGapCount != 0) {
      SeqGapCount = other.SeqGapCount;
    }
    if (other.SampleCount != 0) {
      SampleCount = other.SampleCount;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          AvgD = input.ReadDouble();
          break;
        }
        case 16: {
          MaxD = input.ReadInt32();
          break;
        }
        case 24: {
          PruneCount = input.ReadInt32();
          break;
        }
        case 32: {
          SeqGapCount = input.ReadInt32();
          break;
        }
        case 40: {
          SampleCount = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          AvgD = input.ReadDouble();
          break;
        }
        case 16: {
          MaxD = input.ReadInt32();
          break;
        }
        case 24: {
          PruneCount = input.ReadInt32();
          break;
        }
        case 32: {
          SeqGapCount = input.ReadInt32();
          break;
        }
        case 40: {
          SampleCount = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
