// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InputCommandToS.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from InputCommandToS.proto</summary>
public static partial class InputCommandToSReflection {

  #region Descriptor
  /// <summary>File descriptor for InputCommandToS.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static InputCommandToSReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVJbnB1dENvbW1hbmRUb1MucHJvdG8aEklucHV0Q29tbWFuZC5wcm90bxoU",
          "UHJvdG9UcmFuc2Zvcm0ucHJvdG8iRwoRSW5wdXRDb21tYW5kRW50cnkSDAoE",
          "dGljaxgBIAEoAxIkCg1pbnB1dF9jb21tYW5kGAIgASgLMg0uSW5wdXRDb21t",
          "YW5kIq8BCg9JbnB1dENvbW1hbmRUb1MSEgoKc2Vzc2lvbl9pZBgBIAEoCRIM",
          "CgR0aWNrGAIgASgDEiQKDWlucHV0X2NvbW1hbmQYAyABKAsyDS5JbnB1dENv",
          "bW1hbmQSKQoQZW50aXR5X3RyYW5zZm9ybRgEIAEoCzIPLlByb3RvVHJhbnNm",
          "b3JtEikKDXJlY2VudF9pbnB1dHMYBSADKAsyEi5JbnB1dENvbW1hbmRFbnRy",
          "eWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::InputCommandReflection.Descriptor, global::ProtoTransformReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::InputCommandEntry), global::InputCommandEntry.Parser, new[]{ "Tick", "InputCommand" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::InputCommandToS), global::InputCommandToS.Parser, new[]{ "SessionId", "Tick", "InputCommand", "EntityTransform", "RecentInputs" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 패킷당 redundancy로 묶어 보낼 단일 입력 엔트리(필드 타입 — wire 직접 전송 안 함, 자동 생성 마커 없음 → MessageId 없음).
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class InputCommandEntry : pb::IMessage<InputCommandEntry>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<InputCommandEntry> _parser = new pb::MessageParser<InputCommandEntry>(() => new InputCommandEntry());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<InputCommandEntry> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InputCommandToSReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputCommandEntry() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputCommandEntry(InputCommandEntry other) : this() {
    tick_ = other.tick_;
    inputCommand_ = other.inputCommand_ != null ? other.inputCommand_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputCommandEntry Clone() {
    return new InputCommandEntry(this);
  }

  /// <summary>Field number for the "tick" field.</summary>
  public const int TickFieldNumber = 1;
  private long tick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Tick {
    get { return tick_; }
    set {
      tick_ = value;
    }
  }

  /// <summary>Field number for the "input_command" field.</summary>
  public const int InputCommandFieldNumber = 2;
  private global::InputCommand inputCommand_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::InputCommand InputCommand {
    get { return inputCommand_; }
    set {
      inputCommand_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as InputCommandEntry);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(InputCommandEntry other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Tick != other.Tick) return false;
    if (!object.Equals(InputCommand, other.InputCommand)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Tick != 0L) hash ^= Tick.GetHashCode();
    if (inputCommand_ != null) hash ^= InputCommand.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Tick != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Tick);
    }
    if (inputCommand_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(InputCommand);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Tick != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Tick);
    }
    if (inputCommand_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(InputCommand);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Tick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Tick);
    }
    if (inputCommand_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(InputCommand);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(InputCommandEntry other) {
    if (other == null) {
      return;
    }
    if (other.Tick != 0L) {
      Tick = other.Tick;
    }
    if (other.inputCommand_ != null) {
      if (inputCommand_ == null) {
        InputCommand = new global::InputCommand();
      }
      InputCommand.MergeFrom(other.InputCommand);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Tick = input.ReadInt64();
          break;
        }
        case 18: {
          if (inputCommand_ == null) {
            InputCommand = new global::InputCommand();
          }
          input.ReadMessage(InputCommand);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Tick = input.ReadInt64();
          break;
        }
        case 18: {
          if (inputCommand_ == null) {
            InputCommand = new global::InputCommand();
          }
          input.ReadMessage(InputCommand);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// @auto_generate
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class InputCommandToS : pb::IMessage<InputCommandToS>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<InputCommandToS> _parser = new pb::MessageParser<InputCommandToS>(() => new InputCommandToS());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<InputCommandToS> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InputCommandToSReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputCommandToS() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputCommandToS(InputCommandToS other) : this() {
    sessionId_ = other.sessionId_;
    tick_ = other.tick_;
    inputCommand_ = other.inputCommand_ != null ? other.inputCommand_.Clone() : null;
    entityTransform_ = other.entityTransform_ != null ? other.entityTransform_.Clone() : null;
    recentInputs_ = other.recentInputs_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputCommandToS Clone() {
    return new InputCommandToS(this);
  }

  /// <summary>Field number for the "session_id" field.</summary>
  public const int SessionIdFieldNumber = 1;
  private string sessionId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SessionId {
    get { return sessionId_; }
    set {
      sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "tick" field.</summary>
  public const int TickFieldNumber = 2;
  private long tick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Tick {
    get { return tick_; }
    set {
      tick_ = value;
    }
  }

  /// <summary>Field number for the "input_command" field.</summary>
  public const int InputCommandFieldNumber = 3;
  private global::InputCommand inputCommand_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::InputCommand InputCommand {
    get { return inputCommand_; }
    set {
      inputCommand_ = value;
    }
  }

  /// <summary>Field number for the "entity_transform" field.</summary>
  public const int EntityTransformFieldNumber = 4;
  private global::ProtoTransform entityTransform_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoTransform EntityTransform {
    get { return entityTransform_; }
    set {
      entityTransform_ = value;
    }
  }

  /// <summary>Field number for the "recent_inputs" field.</summary>
  public const int RecentInputsFieldNumber = 5;
  private static readonly pb::FieldCodec<global::InputCommandEntry> _repeated_recentInputs_codec
      = pb::FieldCodec.ForMessage(42, global::InputCommandEntry.Parser);
  private readonly pbc::RepeatedField<global::InputCommandEntry> recentInputs_ = new pbc::RepeatedField<global::InputCommandEntry>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::InputCommandEntry> RecentInputs {
    get { return recentInputs_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as InputCommandToS);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(InputCommandToS other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SessionId != other.SessionId) return false;
    if (Tick != other.Tick) return false;
    if (!object.Equals(InputCommand, other.InputCommand)) return false;
    if (!object.Equals(EntityTransform, other.EntityTransform)) return false;
    if(!recentInputs_.Equals(other.recentInputs_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
    if (Tick != 0L) hash ^= Tick.GetHashCode();
    if (inputCommand_ != null) hash ^= InputCommand.GetHashCode();
    if (entityTransform_ != null) hash ^= EntityTransform.GetHashCode();
    hash ^= recentInputs_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SessionId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SessionId);
    }
    if (Tick != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Tick);
    }
    if (inputCommand_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(InputCommand);
    }
    if (entityTransform_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(EntityTransform);
    }
    recentInputs_.WriteTo(output, _repeated_recentInputs_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SessionId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SessionId);
    }
    if (Tick != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Tick);
    }
    if (inputCommand_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(InputCommand);
    }
    if (entityTransform_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(EntityTransform);
    }
    recentInputs_.WriteTo(ref output, _repeated_recentInputs_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SessionId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
    }
    if (Tick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Tick);
    }
    if (inputCommand_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(InputCommand);
    }
    if (entityTransform_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(EntityTransform);
    }
    size += recentInputs_.CalculateSize(_repeated_recentInputs_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(InputCommandToS other) {
    if (other == null) {
      return;
    }
    if (other.SessionId.Length != 0) {
      SessionId = other.SessionId;
    }
    if (other.Tick != 0L) {
      Tick = other.Tick;
    }
    if (other.inputCommand_ != null) {
      if (inputCommand_ == null) {
        InputCommand = new global::InputCommand();
      }
      InputCommand.MergeFrom(other.InputCommand);
    }
    if (other.entityTransform_ != null) {
      if (entityTransform_ == null) {
        EntityTransform = new global::ProtoTransform();
      }
      EntityTransform.MergeFrom(other.EntityTransform);
    }
    recentInputs_.Add(other.recentInputs_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          SessionId = input.ReadString();
          break;
        }
        case 16: {
          Tick = input.ReadInt64();
          break;
        }
        case 26: {
          if (inputCommand_ == null) {
            InputCommand = new global::InputCommand();
          }
          input.ReadMessage(InputCommand);
          break;
        }
        case 34: {
          if (entityTransform_ == null) {
            EntityTransform = new global::ProtoTransform();
          }
          input.ReadMessage(EntityTransform);
          break;
        }
        case 42: {
          recentInputs_.AddEntriesFrom(input, _repeated_recentInputs_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          SessionId = input.ReadString();
          break;
        }
        case 16: {
          Tick = input.ReadInt64();
          break;
        }
        case 26: {
          if (inputCommand_ == null) {
            InputCommand = new global::InputCommand();
          }
          input.ReadMessage(InputCommand);
          break;
        }
        case 34: {
          if (entityTransform_ == null) {
            EntityTransform = new global::ProtoTransform();
          }
          input.ReadMessage(EntityTransform);
          break;
        }
        case 42: {
          recentInputs_.AddEntriesFrom(ref input, _repeated_recentInputs_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
