// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MatchStartToC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from MatchStartToC.proto</summary>
public static partial class MatchStartToCReflection {

  #region Descriptor
  /// <summary>File descriptor for MatchStartToC.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MatchStartToCReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNNYXRjaFN0YXJ0VG9DLnByb3RvIk0KDU1hdGNoU3RhcnRUb0MSEgoKc3Rh",
          "cnRfdGljaxgBIAEoAxITCgtyZWFkeV9jb3VudBgCIAEoBRITCgt0b3RhbF9j",
          "b3VudBgDIAEoBWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MatchStartToC), global::MatchStartToC.Parser, new[]{ "StartTick", "ReadyCount", "TotalCount" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 출발 예정 틱과 준비 현황. "지금 무슨 상태"가 아니라 "몇 틱에 출발"을 보내는 이유는,
/// 클라가 서버보다 앞선 시계로 달리고 틱을 되감아 재시뮬하기 때문이다 — 현재값으로는
/// "그 틱에 상태가 뭐였나"에 답할 수 없다. MatchEndedToC와 짝이 된다.
/// @auto_generate
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class MatchStartToC : pb::IMessage<MatchStartToC>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MatchStartToC> _parser = new pb::MessageParser<MatchStartToC>(() => new MatchStartToC());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MatchStartToC> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MatchStartToCReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MatchStartToC() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MatchStartToC(MatchStartToC other) : this() {
    startTick_ = other.startTick_;
    readyCount_ = other.readyCount_;
    totalCount_ = other.totalCount_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MatchStartToC Clone() {
    return new MatchStartToC(this);
  }

  /// <summary>Field number for the "start_tick" field.</summary>
  public const int StartTickFieldNumber = 1;
  private long startTick_;
  /// <summary>
  /// 아직 안 정해졌으면 -1
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long StartTick {
    get { return startTick_; }
    set {
      startTick_ = value;
    }
  }

  /// <summary>Field number for the "ready_count" field.</summary>
  public const int ReadyCountFieldNumber = 2;
  private int readyCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ReadyCount {
    get { return readyCount_; }
    set {
      readyCount_ = value;
    }
  }

  /// <summary>Field number for the "total_count" field.</summary>
  public const int TotalCountFieldNumber = 3;
  private int totalCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TotalCount {
    get { return totalCount_; }
    set {
      totalCount_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MatchStartToC);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MatchStartToC other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (StartTick != other.StartTick) return false;
    if (ReadyCount != other.ReadyCount) return false;
    if (TotalCount != other.TotalCount) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (StartTick != 0L) hash ^= StartTick.GetHashCode();
    if (ReadyCount != 0) hash ^= ReadyCount.GetHashCode();
    if (TotalCount != 0) hash ^= TotalCount.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (StartTick != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(StartTick);
    }
    if (ReadyCount != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ReadyCount);
    }
    if (TotalCount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(TotalCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (StartTick != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(StartTick);
    }
    if (ReadyCount != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ReadyCount);
    }
    if (TotalCount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(TotalCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (StartTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartTick);
    }
    if (ReadyCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReadyCount);
    }
    if (TotalCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalCount);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MatchStartToC other) {
    if (other == null) {
      return;
    }
    if (other.StartTick != 0L) {
      StartTick = other.StartTick;
    }
    if (other.ReadyCount != 0) {
      ReadyCount = other.ReadyCount;
    }
    if (other.TotalCount != 0) {
      TotalCount = other.TotalCount;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          StartTick = input.ReadInt64();
          break;
        }
        case 16: {
          ReadyCount = input.ReadInt32();
          break;
        }
        case 24: {
          TotalCount = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          StartTick = input.ReadInt64();
          break;
        }
        case 16: {
          ReadyCount = input.ReadInt32();
          break;
        }
        case 24: {
          TotalCount = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
