// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PanchigiStrikeContact.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PanchigiStrikeContact.proto</summary>
public static partial class PanchigiStrikeContactReflection {

  #region Descriptor
  /// <summary>File descriptor for PanchigiStrikeContact.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PanchigiStrikeContactReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtQYW5jaGlnaVN0cmlrZUNvbnRhY3QucHJvdG8aElByb3RvVmVjdG9yMy5w",
          "cm90byJyChVQYW5jaGlnaVN0cmlrZUNvbnRhY3QSIwoMc3RyaWtlX3BvaW50",
          "GAEgASgLMg0uUHJvdG9WZWN0b3IzEiEKCmRyYWdfZGVsdGEYAiABKAsyDS5Q",
          "cm90b1ZlY3RvcjMSEQoJaG9sZF90aW1lGAMgASgCYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ProtoVector3Reflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PanchigiStrikeContact), global::PanchigiStrikeContact.Parser, new[]{ "StrikePoint", "DragDelta", "HoldTime" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PanchigiStrikeContact : pb::IMessage<PanchigiStrikeContact>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PanchigiStrikeContact> _parser = new pb::MessageParser<PanchigiStrikeContact>(() => new PanchigiStrikeContact());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PanchigiStrikeContact> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PanchigiStrikeContactReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PanchigiStrikeContact() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PanchigiStrikeContact(PanchigiStrikeContact other) : this() {
    strikePoint_ = other.strikePoint_ != null ? other.strikePoint_.Clone() : null;
    dragDelta_ = other.dragDelta_ != null ? other.dragDelta_.Clone() : null;
    holdTime_ = other.holdTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PanchigiStrikeContact Clone() {
    return new PanchigiStrikeContact(this);
  }

  /// <summary>Field number for the "strike_point" field.</summary>
  public const int StrikePointFieldNumber = 1;
  private global::ProtoVector3 strikePoint_;
  /// <summary>
  /// 판 위 월드 좌표
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoVector3 StrikePoint {
    get { return strikePoint_; }
    set {
      strikePoint_ = value;
    }
  }

  /// <summary>Field number for the "drag_delta" field.</summary>
  public const int DragDeltaFieldNumber = 2;
  private global::ProtoVector3 dragDelta_;
  /// <summary>
  /// 판 평면 변위 (y = 0)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoVector3 DragDelta {
    get { return dragDelta_; }
    set {
      dragDelta_ = value;
    }
  }

  /// <summary>Field number for the "hold_time" field.</summary>
  public const int HoldTimeFieldNumber = 3;
  private float holdTime_;
  /// <summary>
  /// 초. 클라가 이미 상한을 적용해 보낸다
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float HoldTime {
    get { return holdTime_; }
    set {
      holdTime_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PanchigiStrikeContact);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PanchigiStrikeContact other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(StrikePoint, other.StrikePoint)) return false;
    if (!object.Equals(DragDelta, other.DragDelta)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(HoldTime, other.HoldTime)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (strikePoint_ != null) hash ^= StrikePoint.GetHashCode();
    if (dragDelta_ != null) hash ^= DragDelta.GetHashCode();
    if (HoldTime != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(HoldTime);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (strikePoint_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(StrikePoint);
    }
    if (dragDelta_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(DragDelta);
    }
    if (HoldTime != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(HoldTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (strikePoint_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(StrikePoint);
    }
    if (dragDelta_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(DragDelta);
    }
    if (HoldTime != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(HoldTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (strikePoint_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(StrikePoint);
    }
    if (dragDelta_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DragDelta);
    }
    if (HoldTime != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PanchigiStrikeContact other) {
    if (other == null) {
      return;
    }
    if (other.strikePoint_ != null) {
      if (strikePoint_ == null) {
        StrikePoint = new global::ProtoVector3();
      }
      StrikePoint.MergeFrom(other.StrikePoint);
    }
    if (other.dragDelta_ != null) {
      if (dragDelta_ == null) {
        DragDelta = new global::ProtoVector3();
      }
      DragDelta.MergeFrom(other.DragDelta);
    }
    if (other.HoldTime != 0F) {
      HoldTime = other.HoldTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (strikePoint_ == null) {
            StrikePoint = new global::ProtoVector3();
          }
          input.ReadMessage(StrikePoint);
          break;
        }
        case 18: {
          if (dragDelta_ == null) {
            DragDelta = new global::ProtoVector3();
          }
          input.ReadMessage(DragDelta);
          break;
        }
        case 29: {
          HoldTime = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (strikePoint_ == null) {
            StrikePoint = new global::ProtoVector3();
          }
          input.ReadMessage(StrikePoint);
          break;
        }
        case 18: {
          if (dragDelta_ == null) {
            DragDelta = new global::ProtoVector3();
          }
          input.ReadMessage(DragDelta);
          break;
        }
        case 29: {
          HoldTime = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
