// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PanchigiStateToC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PanchigiStateToC.proto</summary>
public static partial class PanchigiStateToCReflection {

  #region Descriptor
  /// <summary>File descriptor for PanchigiStateToC.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PanchigiStateToCReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZQYW5jaGlnaVN0YXRlVG9DLnByb3RvIlcKEFBhbmNoaWdpU3RhdGVUb0MS",
          "DQoFcGhhc2UYASABKAUSGQoRY3VycmVudF9lbnRpdHlfaWQYAiABKAkSGQoR",
          "YWltX2RlYWRsaW5lX3RpY2sYAyABKANiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PanchigiStateToC), global::PanchigiStateToC.Parser, new[]{ "Phase", "CurrentEntityId", "AimDeadlineTick" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 판치기 턴 상태(서버 → 클라). 바뀔 때만 reliable로 간다.
/// 남은 시간은 마감을 *틱*으로 보내 클라가 공유 틱 시계로 직접 그린다 — 주기 전송이 필요 없다.
/// @auto_generate
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PanchigiStateToC : pb::IMessage<PanchigiStateToC>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PanchigiStateToC> _parser = new pb::MessageParser<PanchigiStateToC>(() => new PanchigiStateToC());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PanchigiStateToC> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PanchigiStateToCReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PanchigiStateToC() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PanchigiStateToC(PanchigiStateToC other) : this() {
    phase_ = other.phase_;
    currentEntityId_ = other.currentEntityId_;
    aimDeadlineTick_ = other.aimDeadlineTick_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PanchigiStateToC Clone() {
    return new PanchigiStateToC(this);
  }

  /// <summary>Field number for the "phase" field.</summary>
  public const int PhaseFieldNumber = 1;
  private int phase_;
  /// <summary>
  /// 0 = Settling(동전이 구르는 중), 1 = Aiming(누군가 조준 중)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Phase {
    get { return phase_; }
    set {
      phase_ = value;
    }
  }

  /// <summary>Field number for the "current_entity_id" field.</summary>
  public const int CurrentEntityIdFieldNumber = 2;
  private string currentEntityId_ = "";
  /// <summary>
  /// 지금 칠 차례인 플레이어 엔티티. Settling이면 빈 문자열
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CurrentEntityId {
    get { return currentEntityId_; }
    set {
      currentEntityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "aim_deadline_tick" field.</summary>
  public const int AimDeadlineTickFieldNumber = 3;
  private long aimDeadlineTick_;
  /// <summary>
  /// 조준 마감 틱. Aiming일 때만 유효
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long AimDeadlineTick {
    get { return aimDeadlineTick_; }
    set {
      aimDeadlineTick_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PanchigiStateToC);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PanchigiStateToC other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Phase != other.Phase) return false;
    if (CurrentEntityId != other.CurrentEntityId) return false;
    if (AimDeadlineTick != other.AimDeadlineTick) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Phase != 0) hash ^= Phase.GetHashCode();
    if (CurrentEntityId.Length != 0) hash ^= CurrentEntityId.GetHashCode();
    if (AimDeadlineTick != 0L) hash ^= AimDeadlineTick.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Phase != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Phase);
    }
    if (CurrentEntityId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CurrentEntityId);
    }
    if (AimDeadlineTick != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(AimDeadlineTick);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Phase != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Phase);
    }
    if (CurrentEntityId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CurrentEntityId);
    }
    if (AimDeadlineTick != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(AimDeadlineTick);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Phase != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Phase);
    }
    if (CurrentEntityId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentEntityId);
    }
    if (AimDeadlineTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(AimDeadlineTick);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PanchigiStateToC other) {
    if (other == null) {
      return;
    }
    if (other.Phase != 0) {
      Phase = other.Phase;
    }
    if (other.CurrentEntityId.Length != 0) {
      CurrentEntityId = other.CurrentEntityId;
    }
    if (other.AimDeadlineTick != 0L) {
      AimDeadlineTick = other.AimDeadlineTick;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Phase = input.ReadInt32();
          break;
        }
        case 18: {
          CurrentEntityId = input.ReadString();
          break;
        }
        case 24: {
          AimDeadlineTick = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Phase = input.ReadInt32();
          break;
        }
        case 18: {
          CurrentEntityId = input.ReadString();
          break;
        }
        case 24: {
          AimDeadlineTick = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
