// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PanchigiStateToC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PanchigiStateToC.proto</summary>
public static partial class PanchigiStateToCReflection {

  #region Descriptor
  /// <summary>File descriptor for PanchigiStateToC.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PanchigiStateToCReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZQYW5jaGlnaVN0YXRlVG9DLnByb3RvIv8BChBQYW5jaGlnaVN0YXRlVG9D",
          "Eg0KBXBoYXNlGAEgASgFEhkKEWN1cnJlbnRfZW50aXR5X2lkGAIgASgJEhkK",
          "EWFpbV9kZWFkbGluZV90aWNrGAMgASgDEj0KD2Ryb3Bfb3V0X2NvdW50cxgE",
          "IAMoCzIkLlBhbmNoaWdpU3RhdGVUb0MuRHJvcE91dENvdW50c0VudHJ5Eh0K",
          "FWVsaW1pbmF0ZWRfZW50aXR5X2lkcxgFIAMoCRISCgp0dXJuX2NvdW50GAYg",
          "ASgFGjQKEkRyb3BPdXRDb3VudHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFs",
          "dWUYAiABKAU6AjgBYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PanchigiStateToC), global::PanchigiStateToC.Parser, new[]{ "Phase", "CurrentEntityId", "AimDeadlineTick", "DropOutCounts", "EliminatedEntityIds", "TurnCount" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 판치기 턴 상태(서버 → 클라). 바뀔 때만 reliable로 간다.
/// 남은 시간은 마감을 *틱*으로 보내 클라가 공유 틱 시계로 직접 그린다 — 주기 전송이 필요 없다.
/// @auto_generate
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PanchigiStateToC : pb::IMessage<PanchigiStateToC>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PanchigiStateToC> _parser = new pb::MessageParser<PanchigiStateToC>(() => new PanchigiStateToC());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PanchigiStateToC> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PanchigiStateToCReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PanchigiStateToC() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PanchigiStateToC(PanchigiStateToC other) : this() {
    phase_ = other.phase_;
    currentEntityId_ = other.currentEntityId_;
    aimDeadlineTick_ = other.aimDeadlineTick_;
    dropOutCounts_ = other.dropOutCounts_.Clone();
    eliminatedEntityIds_ = other.eliminatedEntityIds_.Clone();
    turnCount_ = other.turnCount_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PanchigiStateToC Clone() {
    return new PanchigiStateToC(this);
  }

  /// <summary>Field number for the "phase" field.</summary>
  public const int PhaseFieldNumber = 1;
  private int phase_;
  /// <summary>
  /// 0 = Settling(동전이 구르는 중), 1 = Aiming(누군가 조준 중)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Phase {
    get { return phase_; }
    set {
      phase_ = value;
    }
  }

  /// <summary>Field number for the "current_entity_id" field.</summary>
  public const int CurrentEntityIdFieldNumber = 2;
  private string currentEntityId_ = "";
  /// <summary>
  /// 지금 칠 차례인 플레이어 엔티티. Settling이면 빈 문자열
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CurrentEntityId {
    get { return currentEntityId_; }
    set {
      currentEntityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "aim_deadline_tick" field.</summary>
  public const int AimDeadlineTickFieldNumber = 3;
  private long aimDeadlineTick_;
  /// <summary>
  /// 조준 마감 틱. Aiming일 때만 유효
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long AimDeadlineTick {
    get { return aimDeadlineTick_; }
    set {
      aimDeadlineTick_ = value;
    }
  }

  /// <summary>Field number for the "drop_out_counts" field.</summary>
  public const int DropOutCountsFieldNumber = 4;
  private static readonly pbc::MapField<string, int>.Codec _map_dropOutCounts_codec
      = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 34);
  private readonly pbc::MapField<string, int> dropOutCounts_ = new pbc::MapField<string, int>();
  /// <summary>
  /// 플레이어 엔티티별 낙(落) 횟수. 한 번도 안 떨어뜨린 사람은 아예 안 들어온다.
  /// 한도(몇 번까지 봐주는지)는 클라도 마스터데이터에서 직접 읽으므로 싣지 않는다.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, int> DropOutCounts {
    get { return dropOutCounts_; }
  }

  /// <summary>Field number for the "eliminated_entity_ids" field.</summary>
  public const int EliminatedEntityIdsFieldNumber = 5;
  private static readonly pb::FieldCodec<string> _repeated_eliminatedEntityIds_codec
      = pb::FieldCodec.ForString(42);
  private readonly pbc::RepeatedField<string> eliminatedEntityIds_ = new pbc::RepeatedField<string>();
  /// <summary>
  /// 판에서 빠진(탈락한) 플레이어 엔티티들
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> EliminatedEntityIds {
    get { return eliminatedEntityIds_; }
  }

  /// <summary>Field number for the "turn_count" field.</summary>
  public const int TurnCountFieldNumber = 6;
  private int turnCount_;
  /// <summary>
  /// 지금까지 지나간 턴 수(친 것 + 패스한 것). 상한은 클라도 마스터데이터에서 직접 읽는다.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TurnCount {
    get { return turnCount_; }
    set {
      turnCount_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PanchigiStateToC);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PanchigiStateToC other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Phase != other.Phase) return false;
    if (CurrentEntityId != other.CurrentEntityId) return false;
    if (AimDeadlineTick != other.AimDeadlineTick) return false;
    if (!DropOutCounts.Equals(other.DropOutCounts)) return false;
    if(!eliminatedEntityIds_.Equals(other.eliminatedEntityIds_)) return false;
    if (TurnCount != other.TurnCount) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Phase != 0) hash ^= Phase.GetHashCode();
    if (CurrentEntityId.Length != 0) hash ^= CurrentEntityId.GetHashCode();
    if (AimDeadlineTick != 0L) hash ^= AimDeadlineTick.GetHashCode();
    hash ^= DropOutCounts.GetHashCode();
    hash ^= eliminatedEntityIds_.GetHashCode();
    if (TurnCount != 0) hash ^= TurnCount.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Phase != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Phase);
    }
    if (CurrentEntityId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CurrentEntityId);
    }
    if (AimDeadlineTick != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(AimDeadlineTick);
    }
    dropOutCounts_.WriteTo(output, _map_dropOutCounts_codec);
    eliminatedEntityIds_.WriteTo(output, _repeated_eliminatedEntityIds_codec);
    if (TurnCount != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(TurnCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Phase != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Phase);
    }
    if (CurrentEntityId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CurrentEntityId);
    }
    if (AimDeadlineTick != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(AimDeadlineTick);
    }
    dropOutCounts_.WriteTo(ref output, _map_dropOutCounts_codec);
    eliminatedEntityIds_.WriteTo(ref output, _repeated_eliminatedEntityIds_codec);
    if (TurnCount != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(TurnCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Phase != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Phase);
    }
    if (CurrentEntityId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CurrentEntityId);
    }
    if (AimDeadlineTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(AimDeadlineTick);
    }
    size += dropOutCounts_.CalculateSize(_map_dropOutCounts_codec);
    size += eliminatedEntityIds_.CalculateSize(_repeated_eliminatedEntityIds_codec);
    if (TurnCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TurnCount);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PanchigiStateToC other) {
    if (other == null) {
      return;
    }
    if (other.Phase != 0) {
      Phase = other.Phase;
    }
    if (other.CurrentEntityId.Length != 0) {
      CurrentEntityId = other.CurrentEntityId;
    }
    if (other.AimDeadlineTick != 0L) {
      AimDeadlineTick = other.AimDeadlineTick;
    }
    dropOutCounts_.MergeFrom(other.dropOutCounts_);
    eliminatedEntityIds_.Add(other.eliminatedEntityIds_);
    if (other.TurnCount != 0) {
      TurnCount = other.TurnCount;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Phase = input.ReadInt32();
          break;
        }
        case 18: {
          CurrentEntityId = input.ReadString();
          break;
        }
        case 24: {
          AimDeadlineTick = input.ReadInt64();
          break;
        }
        case 34: {
          dropOutCounts_.AddEntriesFrom(input, _map_dropOutCounts_codec);
          break;
        }
        case 42: {
          eliminatedEntityIds_.AddEntriesFrom(input, _repeated_eliminatedEntityIds_codec);
          break;
        }
        case 48: {
          TurnCount = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Phase = input.ReadInt32();
          break;
        }
        case 18: {
          CurrentEntityId = input.ReadString();
          break;
        }
        case 24: {
          AimDeadlineTick = input.ReadInt64();
          break;
        }
        case 34: {
          dropOutCounts_.AddEntriesFrom(ref input, _map_dropOutCounts_codec);
          break;
        }
        case 42: {
          eliminatedEntityIds_.AddEntriesFrom(ref input, _repeated_eliminatedEntityIds_codec);
          break;
        }
        case 48: {
          TurnCount = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
