// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoActiveEffect.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ProtoActiveEffect.proto</summary>
public static partial class ProtoActiveEffectReflection {

  #region Descriptor
  /// <summary>File descriptor for ProtoActiveEffect.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProtoActiveEffectReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdQcm90b0FjdGl2ZUVmZmVjdC5wcm90byJQChFQcm90b0FjdGl2ZUVmZmVj",
          "dBIRCgllZmZlY3RfaWQYASABKAUSEwoLZXhwaXJlX3RpY2sYAiABKAMSEwoL",
          "c3RhY2tfY291bnQYAyABKAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoActiveEffect), global::ProtoActiveEffect.Parser, new[]{ "EffectId", "ExpireTick", "StackCount" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ProtoActiveEffect : pb::IMessage<ProtoActiveEffect>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoActiveEffect> _parser = new pb::MessageParser<ProtoActiveEffect>(() => new ProtoActiveEffect());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoActiveEffect> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtoActiveEffectReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoActiveEffect() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoActiveEffect(ProtoActiveEffect other) : this() {
    effectId_ = other.effectId_;
    expireTick_ = other.expireTick_;
    stackCount_ = other.stackCount_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoActiveEffect Clone() {
    return new ProtoActiveEffect(this);
  }

  /// <summary>Field number for the "effect_id" field.</summary>
  public const int EffectIdFieldNumber = 1;
  private int effectId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int EffectId {
    get { return effectId_; }
    set {
      effectId_ = value;
    }
  }

  /// <summary>Field number for the "expire_tick" field.</summary>
  public const int ExpireTickFieldNumber = 2;
  private long expireTick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long ExpireTick {
    get { return expireTick_; }
    set {
      expireTick_ = value;
    }
  }

  /// <summary>Field number for the "stack_count" field.</summary>
  public const int StackCountFieldNumber = 3;
  private int stackCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int StackCount {
    get { return stackCount_; }
    set {
      stackCount_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoActiveEffect);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoActiveEffect other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EffectId != other.EffectId) return false;
    if (ExpireTick != other.ExpireTick) return false;
    if (StackCount != other.StackCount) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EffectId != 0) hash ^= EffectId.GetHashCode();
    if (ExpireTick != 0L) hash ^= ExpireTick.GetHashCode();
    if (StackCount != 0) hash ^= StackCount.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EffectId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(EffectId);
    }
    if (ExpireTick != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(ExpireTick);
    }
    if (StackCount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(StackCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EffectId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(EffectId);
    }
    if (ExpireTick != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(ExpireTick);
    }
    if (StackCount != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(StackCount);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EffectId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(EffectId);
    }
    if (ExpireTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(ExpireTick);
    }
    if (StackCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(StackCount);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoActiveEffect other) {
    if (other == null) {
      return;
    }
    if (other.EffectId != 0) {
      EffectId = other.EffectId;
    }
    if (other.ExpireTick != 0L) {
      ExpireTick = other.ExpireTick;
    }
    if (other.StackCount != 0) {
      StackCount = other.StackCount;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          EffectId = input.ReadInt32();
          break;
        }
        case 16: {
          ExpireTick = input.ReadInt64();
          break;
        }
        case 24: {
          StackCount = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          EffectId = input.ReadInt32();
          break;
        }
        case 16: {
          ExpireTick = input.ReadInt64();
          break;
        }
        case 24: {
          StackCount = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
