// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoMotionContribution.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ProtoMotionContribution.proto</summary>
public static partial class ProtoMotionContributionReflection {

  #region Descriptor
  /// <summary>File descriptor for ProtoMotionContribution.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProtoMotionContributionReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch1Qcm90b01vdGlvbkNvbnRyaWJ1dGlvbi5wcm90bxoSUHJvdG9WZWN0b3Iz",
          "LnByb3RvIpoBChdQcm90b01vdGlvbkNvbnRyaWJ1dGlvbhIhCgpob3Jpem9u",
          "dGFsGAEgASgLMg0uUHJvdG9WZWN0b3IzEgwKBG1vZGUYAiABKAUSEAoIcHJp",
          "b3JpdHkYAyABKAUSEgoKc3RhcnRfdGljaxgEIAEoAxIQCghlbmRfdGljaxgF",
          "IAEoAxIWCg5kZWNheV9wZXJfdGljaxgGIAEoAmIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ProtoVector3Reflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoMotionContribution), global::ProtoMotionContribution.Parser, new[]{ "Horizontal", "Mode", "Priority", "StartTick", "EndTick", "DecayPerTick" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ProtoMotionContribution : pb::IMessage<ProtoMotionContribution>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoMotionContribution> _parser = new pb::MessageParser<ProtoMotionContribution>(() => new ProtoMotionContribution());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoMotionContribution> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtoMotionContributionReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoMotionContribution() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoMotionContribution(ProtoMotionContribution other) : this() {
    horizontal_ = other.horizontal_ != null ? other.horizontal_.Clone() : null;
    mode_ = other.mode_;
    priority_ = other.priority_;
    startTick_ = other.startTick_;
    endTick_ = other.endTick_;
    decayPerTick_ = other.decayPerTick_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoMotionContribution Clone() {
    return new ProtoMotionContribution(this);
  }

  /// <summary>Field number for the "horizontal" field.</summary>
  public const int HorizontalFieldNumber = 1;
  private global::ProtoVector3 horizontal_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ProtoVector3 Horizontal {
    get { return horizontal_; }
    set {
      horizontal_ = value;
    }
  }

  /// <summary>Field number for the "mode" field.</summary>
  public const int ModeFieldNumber = 2;
  private int mode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Mode {
    get { return mode_; }
    set {
      mode_ = value;
    }
  }

  /// <summary>Field number for the "priority" field.</summary>
  public const int PriorityFieldNumber = 3;
  private int priority_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Priority {
    get { return priority_; }
    set {
      priority_ = value;
    }
  }

  /// <summary>Field number for the "start_tick" field.</summary>
  public const int StartTickFieldNumber = 4;
  private long startTick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long StartTick {
    get { return startTick_; }
    set {
      startTick_ = value;
    }
  }

  /// <summary>Field number for the "end_tick" field.</summary>
  public const int EndTickFieldNumber = 5;
  private long endTick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long EndTick {
    get { return endTick_; }
    set {
      endTick_ = value;
    }
  }

  /// <summary>Field number for the "decay_per_tick" field.</summary>
  public const int DecayPerTickFieldNumber = 6;
  private float decayPerTick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float DecayPerTick {
    get { return decayPerTick_; }
    set {
      decayPerTick_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoMotionContribution);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoMotionContribution other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Horizontal, other.Horizontal)) return false;
    if (Mode != other.Mode) return false;
    if (Priority != other.Priority) return false;
    if (StartTick != other.StartTick) return false;
    if (EndTick != other.EndTick) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DecayPerTick, other.DecayPerTick)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (horizontal_ != null) hash ^= Horizontal.GetHashCode();
    if (Mode != 0) hash ^= Mode.GetHashCode();
    if (Priority != 0) hash ^= Priority.GetHashCode();
    if (StartTick != 0L) hash ^= StartTick.GetHashCode();
    if (EndTick != 0L) hash ^= EndTick.GetHashCode();
    if (DecayPerTick != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DecayPerTick);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (horizontal_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Horizontal);
    }
    if (Mode != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Mode);
    }
    if (Priority != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Priority);
    }
    if (StartTick != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(StartTick);
    }
    if (EndTick != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(EndTick);
    }
    if (DecayPerTick != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(DecayPerTick);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (horizontal_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Horizontal);
    }
    if (Mode != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Mode);
    }
    if (Priority != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Priority);
    }
    if (StartTick != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(StartTick);
    }
    if (EndTick != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(EndTick);
    }
    if (DecayPerTick != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(DecayPerTick);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (horizontal_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Horizontal);
    }
    if (Mode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Mode);
    }
    if (Priority != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Priority);
    }
    if (StartTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartTick);
    }
    if (EndTick != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndTick);
    }
    if (DecayPerTick != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoMotionContribution other) {
    if (other == null) {
      return;
    }
    if (other.horizontal_ != null) {
      if (horizontal_ == null) {
        Horizontal = new global::ProtoVector3();
      }
      Horizontal.MergeFrom(other.Horizontal);
    }
    if (other.Mode != 0) {
      Mode = other.Mode;
    }
    if (other.Priority != 0) {
      Priority = other.Priority;
    }
    if (other.StartTick != 0L) {
      StartTick = other.StartTick;
    }
    if (other.EndTick != 0L) {
      EndTick = other.EndTick;
    }
    if (other.DecayPerTick != 0F) {
      DecayPerTick = other.DecayPerTick;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (horizontal_ == null) {
            Horizontal = new global::ProtoVector3();
          }
          input.ReadMessage(Horizontal);
          break;
        }
        case 16: {
          Mode = input.ReadInt32();
          break;
        }
        case 24: {
          Priority = input.ReadInt32();
          break;
        }
        case 32: {
          StartTick = input.ReadInt64();
          break;
        }
        case 40: {
          EndTick = input.ReadInt64();
          break;
        }
        case 53: {
          DecayPerTick = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (horizontal_ == null) {
            Horizontal = new global::ProtoVector3();
          }
          input.ReadMessage(Horizontal);
          break;
        }
        case 16: {
          Mode = input.ReadInt32();
          break;
        }
        case 24: {
          Priority = input.ReadInt32();
          break;
        }
        case 32: {
          StartTick = input.ReadInt64();
          break;
        }
        case 40: {
          EndTick = input.ReadInt64();
          break;
        }
        case 53: {
          DecayPerTick = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
