// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WorldEventToC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from WorldEventToC.proto</summary>
public static partial class WorldEventToCReflection {

  #region Descriptor
  /// <summary>File descriptor for WorldEventToC.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static WorldEventToCReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNXb3JsZEV2ZW50VG9DLnByb3RvGhREYW1hZ2VFdmVudFRvQy5wcm90bxoZ",
          "QWJpbGl0eUFjdGl2YXRlZFRvQy5wcm90byJuCg1Xb3JsZEV2ZW50VG9DEiEK",
          "BmRhbWFnZRgBIAEoCzIPLkRhbWFnZUV2ZW50VG9DSAASMQoRYWJpbGl0eV9h",
          "Y3RpdmF0ZWQYAiABKAsyFC5BYmlsaXR5QWN0aXZhdGVkVG9DSABCBwoFZXZl",
          "bnRiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::DamageEventToCReflection.Descriptor, global::AbilityActivatedToCReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::WorldEventToC), global::WorldEventToC.Parser, new[]{ "Damage", "AbilityActivated" }, new[]{ "Event" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 폴리모픽 래퍼 — top-level 패킷 아님(@auto_generate 없음). WorldEventBatchToC 안에 담긴다.
/// 새 WorldEvent 타입 = oneof에 한 줄 추가.
/// </summary>
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class WorldEventToC : pb::IMessage<WorldEventToC>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<WorldEventToC> _parser = new pb::MessageParser<WorldEventToC>(() => new WorldEventToC());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<WorldEventToC> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WorldEventToCReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WorldEventToC() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WorldEventToC(WorldEventToC other) : this() {
    switch (other.EventCase) {
      case EventOneofCase.Damage:
        Damage = other.Damage.Clone();
        break;
      case EventOneofCase.AbilityActivated:
        AbilityActivated = other.AbilityActivated.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public WorldEventToC Clone() {
    return new WorldEventToC(this);
  }

  /// <summary>Field number for the "damage" field.</summary>
  public const int DamageFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DamageEventToC Damage {
    get { return eventCase_ == EventOneofCase.Damage ? (global::DamageEventToC) event_ : null; }
    set {
      event_ = value;
      eventCase_ = value == null ? EventOneofCase.None : EventOneofCase.Damage;
    }
  }

  /// <summary>Field number for the "ability_activated" field.</summary>
  public const int AbilityActivatedFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AbilityActivatedToC AbilityActivated {
    get { return eventCase_ == EventOneofCase.AbilityActivated ? (global::AbilityActivatedToC) event_ : null; }
    set {
      event_ = value;
      eventCase_ = value == null ? EventOneofCase.None : EventOneofCase.AbilityActivated;
    }
  }

  private object event_;
  /// <summary>Enum of possible cases for the "event" oneof.</summary>
  public enum EventOneofCase {
    None = 0,
    Damage = 1,
    AbilityActivated = 2,
  }
  private EventOneofCase eventCase_ = EventOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EventOneofCase EventCase {
    get { return eventCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearEvent() {
    eventCase_ = EventOneofCase.None;
    event_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as WorldEventToC);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(WorldEventToC other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Damage, other.Damage)) return false;
    if (!object.Equals(AbilityActivated, other.AbilityActivated)) return false;
    if (EventCase != other.EventCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (eventCase_ == EventOneofCase.Damage) hash ^= Damage.GetHashCode();
    if (eventCase_ == EventOneofCase.AbilityActivated) hash ^= AbilityActivated.GetHashCode();
    hash ^= (int) eventCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (eventCase_ == EventOneofCase.Damage) {
      output.WriteRawTag(10);
      output.WriteMessage(Damage);
    }
    if (eventCase_ == EventOneofCase.AbilityActivated) {
      output.WriteRawTag(18);
      output.WriteMessage(AbilityActivated);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (eventCase_ == EventOneofCase.Damage) {
      output.WriteRawTag(10);
      output.WriteMessage(Damage);
    }
    if (eventCase_ == EventOneofCase.AbilityActivated) {
      output.WriteRawTag(18);
      output.WriteMessage(AbilityActivated);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (eventCase_ == EventOneofCase.Damage) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Damage);
    }
    if (eventCase_ == EventOneofCase.AbilityActivated) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(AbilityActivated);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(WorldEventToC other) {
    if (other == null) {
      return;
    }
    switch (other.EventCase) {
      case EventOneofCase.Damage:
        if (Damage == null) {
          Damage = new global::DamageEventToC();
        }
        Damage.MergeFrom(other.Damage);
        break;
      case EventOneofCase.AbilityActivated:
        if (AbilityActivated == null) {
          AbilityActivated = new global::AbilityActivatedToC();
        }
        AbilityActivated.MergeFrom(other.AbilityActivated);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::DamageEventToC subBuilder = new global::DamageEventToC();
          if (eventCase_ == EventOneofCase.Damage) {
            subBuilder.MergeFrom(Damage);
          }
          input.ReadMessage(subBuilder);
          Damage = subBuilder;
          break;
        }
        case 18: {
          global::AbilityActivatedToC subBuilder = new global::AbilityActivatedToC();
          if (eventCase_ == EventOneofCase.AbilityActivated) {
            subBuilder.MergeFrom(AbilityActivated);
          }
          input.ReadMessage(subBuilder);
          AbilityActivated = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::DamageEventToC subBuilder = new global::DamageEventToC();
          if (eventCase_ == EventOneofCase.Damage) {
            subBuilder.MergeFrom(Damage);
          }
          input.ReadMessage(subBuilder);
          Damage = subBuilder;
          break;
        }
        case 18: {
          global::AbilityActivatedToC subBuilder = new global::AbilityActivatedToC();
          if (eventCase_ == EventOneofCase.AbilityActivated) {
            subBuilder.MergeFrom(AbilityActivated);
          }
          input.ReadMessage(subBuilder);
          AbilityActivated = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
